### ISSUE TITLE
Connecting user_data with callbacks

### ISSUE THREAD

**Issue by Hackerpilot** [gtkd-developers/GtkD#108]
The "clicked" signal handler is defined by GTK as 
```c
void user_function (GtkButton *button, gpointer   user_data)
```
But in GtkD addOnClicked() takes a delegate that only takes a reference to the button. How do I associate data with a click handler other than maintaining my own mapping of Button -> data?

**Comment by MikeWey** [comment]
That would depend on the use case.

the delegate passed to addOnClicked has access to it's context, so it might be able to access the data directly.

Or you could do what you do in C and use the gobject.Signals,connectData functions directly, but those expect a function with the C types as parameters.

**Comment by Hackerpilot** [comment]
I was hoping to have a way to translate
```c
for(i = 0; i < 10; i++)
{
    g_object_connect(button, "clicked", &callback, i);
}
```
into
```d
foreach (i; 0 .. 10)
{
    button.addOnClicked(&someMemberFunction, i);
}
```
without having to declare the function in the context of the call to addOnClicked, but that may not be possible.

**Comment by Hackerpilot** [comment]
```d
import std.stdio;

void delegate()[] getFunctions()
{
	typeof(return) retVal;
	foreach (i; 0 .. 10)
	{
		retVal ~= { immutable j = i; writeln(j); };
	}
	return retVal;
}

void main(string[] args)
{
	auto delegates = getFunctions();
	foreach (d; delegates)
		d();
}
```
This program prints "9" 10 times, so this approach won't work either.

The other solution that I thought of is creating a class member of type `myData[size_t]` and casting the button pointer to size_t so that each button would be able to know which item of the ListBox it's supposed to be operating on.

Is there really no better way to do this in GtkD?

**Comment by Hackerpilot** [comment]
Maybe this would work better:
```d
import std.stdio;

void delegate() getFunction(size_t i)
{
	return { immutable j = i; writeln(j); };
}

void delegate()[] getFunctions()
{
	typeof(return) retVal;
	foreach (i; 0 .. 10)
		retVal ~= getFunction(i);
	return retVal;
}

void main(string[] args)
{
	auto delegates = getFunctions();
	foreach (d; delegates)
		d();
}
```
```
0
1
2
3
4
5
6
7
8
9
```

**Comment by MikeWey** [comment]
That's  a nice solution.

Something like this would also work:

```D
for (i = 0; i < 10; i++)
{
    Signals.connectData(button.getButtonStruct(), "clicked", cast(GCallback)&callback, i, null, null);
}

extern(C) void callback(GtkButton* button, void* user_data)
{
    realFunc(ObjectG.getDObject!(Button)(button), cast(size_t)i);
}
```

**Comment by Hackerpilot** [comment]
Where is the documentation for those bits of GtkD-specific functionality? I didn't know that the ObjectG.getDObject function existed or what it did.

**Comment by MikeWey** [comment]
getDObject is/was? meant for internal use, and isn't currently documented.

It turns a GTK handle into a GtkD Object, returning a preexisting object if one exists.

**Comment by MikeWey** [comment]
http://api.gtkd.org/src/gobject/ObjectG.html#ObjectG.getDObject
