### ISSUE TITLE
Pixbuf is broken in 3.1.1 and 3.1.2

### ISSUE THREAD

**Issue by SingingBush** [gtkd-developers/GtkD#115]
it used to be that `getPixels()` in `gdkpixbuf/Pixbuf.d` returned a pointer. Even the docs for the method say it returns a pointer but yet the current code is returning a string:

	public string getPixels()
	{
		return Str.toString(gdk_pixbuf_get_pixels(gdkPixbuf));
	}

that can't be right. Also the same with `getPixelsWithLength()` is now returning string instead of char array.

Is there something wrong with the way that GTK is getting wrapped?

**Comment by MikeWey** [comment]
The wrapper infers is as a sting while that isn't the case.

**Comment by MikeWey** [comment]
The last two functions are fixed in commit: e17406f4ec0559f9eaa786d0fec84c36e9e0702a
