### ISSUE TITLE
Generating the wrapper fails

### ISSUE THREAD

**Issue by ff2000** [gtkd-developers/GtkD#119]
Running gtkwrap immediately gives an error in Atk:
```Text
copying file [./paths.d] to [../src/gtkc/paths.d]
copying file [./Loader.d] to [../src/gtkc/Loader.d]
utils.WrapError.WrapError@./APILookupAtk.txt(91): unknown function get_binary_age
```
atk/atkversion.h contains
```C
ATK_AVAILABLE_IN_2_8
guint atk_get_binary_age    (void) G_GNUC_CONST;
```
So the symbol is there. I have atk-2.16 installed.

**Comment by MikeWey** [comment]
Is the get_binary_age function defined in the GIR file on your system?

For me its on line 15179 in /usr/share/gir-1.0/Atk-1.0.gir.

**Comment by ff2000** [comment]
Mike Wey wrote:
> Is the get_binary_age function defined in the GIR file on your system?
> 
> For me its on line 15179 in /usr/share/gir-1.0/Atk-1.0.gir.

No, get_binary_age is not defined in Atk-1.0.gir.
I am using Gentoo linux and the introspection files are generated during build time, it simply passes --enable-introspection=yes to the configure script. Is this a bug in Atk or gobject-introspection?

**Comment by ff2000** [comment]
This might turn out to be a Gentoo issue. I reported it here:
https://bugs.gentoo.org/show_bug.cgi?id=554506

I found out that if I run ./configure --enable-introspection=yes on the atk-2.16.0 sources those symbols are actually present in Atk-1.0.gir.

**Comment by ff2000** [comment]
This got fixed in Gentoo. Atk seems to have issues with out-of-source-build.
