### ISSUE TITLE
Missing support for "glib:boxed" tag

### ISSUE THREAD

**Issue by ff2000** [gtkd-developers/GtkD#120]
I need to add Soup for WebKit2. But Soup throws an error:
```
core.exception.AssertError@utils/GtkPackage.d(179): Unexpected tag: glib:boxed
```
Is this about [boxed types](https://developer.gnome.org/gobject/stable/gobject-Boxed-Types.html)?

Furthermore the error message could be a little bit more useful ;) Like printing the gir-file it currently is parsing and te line number that threw the error. I added JavaScriptCore at the same time and needed to comment out several lines in order to find the offending package.

**Comment by MikeWey** [comment]
Yes that tag in the gir files define a boxed type, it looks like the type defined by soup: SoupByteArray is never used. is this correct, im skipping the glib:boxed tag for now: ca44ca2905f0ac40790353f5ae100770dace20ce

Line numbers would be a good addition, the XMLReader now counts the lines (629329d2767aadca4fe2dd0bff4697005c3942f4), still need to work on the error messages.

**Comment by MikeWey** [comment]
Error messages with line numbers were added in: 04cb2ee2e850d69e84787985a49be0f6969c9232
