### ISSUE TITLE
GTK print dialog

### ISSUE THREAD

**Issue by dino99** [gtkd-developers/GtkD#126]
When i print a pdf (or else) file under a gnome-shell (3.16.3) session, i expect to get all the data/settings/info in the same place.
But there is no tab to find/list/display the job queue;
 and its a real pain to find/use external commands/features to get the unknown jobs list left by an other session.

This problem has first been reported on Launchpad as lp:1468624
As per Till comment (#7) i'm reporting that request here.

**Comment by MikeWey** [comment]
If i understand it correctly this is a problem with GTK itself, and also affects GTK apps not using GtkD?

If that's the case, it would be best to report it upstream: https://bugzilla.gnome.org/.

**Comment by dino99** [comment]
ok, filed on bugzilla. Thanks Mike
https://bugzilla.gnome.org/show_bug.cgi?id=754346
