### ISSUE TITLE
pixbuf scale_simple leak memory ?

### ISSUE THREAD

**Issue by passenger94** [gtkd-developers/GtkD#127]
Maybe i'm doing it wrong, if so could you shed some light on this, please :-)
Thanks for your time !

```D
import  std.stdio, std.algorithm, std.string;
import  gtk.Main, gtk.Window, gdk.Event, gdk.Keysyms, gtk.Widget, 
            gtk.Image, gdkpixbuf.Pixbuf;

class ViewWindow : Window
{
  private Image imgWidget;
  private Pixbuf cachedPixbuf;

  this() {
    super("pixbuf scale Demo");
    setSizeRequest(400, 300);
    addOnDelete( (Event ev, Widget w) {Main.quit; return true;} );
    addOnKeyPress( &keyPressed );

    imgWidget = new Image();
    add(imgWidget);

    cachedPixbuf = new Pixbuf("path/to/someFatFile");

    setimg();
  }

  void setimg() {
    imgWidget.setFromPixbuf( cachedPixbuf.scaleSimple(400,300, InterpType.BILINEAR) );
//    writefln("cachedPixbuf reCount %s", (cast(GObject*)cachedPixbuf.getPixbufStruct).refCount);
  }

  bool keyPressed(GdkEventKey* ev, Widget w) {
    if (ev.keyval == GdkKeysyms.GDK_Left) {
      setimg();
      return true;
    }
    return false;
  }
}


void main(string[] args)
{
  version (unittest) {} else {
    
    Main.init(args);
    
    auto win = new ViewWindow();
    win.showAll();

    Main.run();
  }
}
```

Same in Vala to check it's valid
```Vala
using Gtk;

public class ViewWindow : Window {

    private Image imgWidget;
    private Gdk.Pixbuf cachedPixbuf;

    public ViewWindow() {
        add_events(Gdk.EventMask.BUTTON_PRESS_MASK
                 | Gdk.EventMask.BUTTON_RELEASE_MASK);
                 
        this.key_press_event.connect (on_key_pressed);
        
        imgWidget = new Image();
        add(this.imgWidget);
        
        try { cachedPixbuf = new Gdk.Pixbuf.from_file("path/to/someFatFile");
        } catch (Error e) { error ("%s", e.message); }
        
        setimg();
    }
    
    void setimg() {
        stdout.printf("scaling\n");
        imgWidget.set_from_pixbuf( this.cachedPixbuf.scale_simple(400, 300, Gdk.InterpType.BILINEAR ) );
    }
    
    private bool on_key_pressed (Widget source, Gdk.EventKey ev) {
        if (ev.keyval == Gdk.Key.Left) {
            setimg();
            return true;
        }
        return false;
    }
}

int main (string[] args) {
    Gtk.init(ref args);

    var window = new ViewWindow();
    window.set_default_size (400, 300);
    window.destroy.connect(Gtk.main_quit);

    window.show_all();

    Gtk.main();
    return 0;
}

```

in Vala, it doesn't leak at all;
simply checked with my "system monitor process" (whatever the name), as i noticed, while experimenting with a simple image viewer app, huge leaks and whole system slowing down with bloated memory !!
Simply press **Left** key on keyboard and watch the app eating memory ...

After simplifying and testing in another language it "looks" like it happens in gtkD only
At first i thought i was doing some bad memory management with not unref()-ing  Pixbuf but after a lot of debugging, i didn't found anything within my knowledge frame  ...

Ubuntu 14.04, gtkd 3.1.4, gtk 3.10, dmd 2.068, dub 0.9.23
Cheers

**Comment by MikeWey** [comment]
I don't see anything wrong at first hand, i'll see what i can find.

**Comment by passenger94** [comment]
hi @MikeWey 
just to let you know
it happens for every function that returns a new Pixbuf : rotateSimple, addAlpha, flip,..., applyEmbeddedOrientation is interesting because it do leaks when the image actually needs to be rotated and therefore a copy is made, but do not (as expected) when just increasing the ref count.
i guess some pixels are not released/freed somewhere at the end of the copy
btw valgrind confirms a huge leak of memory (be it my fault or not ;-)  ) i have a log if you need ...

**Comment by MikeWey** [comment]
It isn't leaking any memory, it's just the GC isn't running a collection cycle.
Probably because the GC just sees the GtkD object and not the image data it holds, bacause thats on the C heap.

Adding `GC.collect()` to setimg to force the GC to run keeps the memory usage constant.
So when doing something like this you probably want to use `object.destroy` on the pixbuf.
http://dlang.org/phobos/object.html#.destroy

As for valgrind, it doesn't know about the garbage collector, so it will show memory leeks for things that are relying on the GC.

**Comment by passenger94** [comment]
ok i think i have it ...
setimg above in the D version should be :
```D
  void setimg() {
    auto pb = cachedPixbuf.scaleSimple(400,300, InterpType.BILINEAR);
    imgWidget.setFromPixbuf( pb );
    scope(exit) pb.unref();
  }
```
**pb.unref()** alone ( without scope(exit) ) crashes as well as **pb.destroy()**
apparently it's mandatory to catch the return of scale, rotate, etc... methods in an object and then unref it once outside of the scope.
Might be a cleaner/more generic way of managing this ?

**Comment by passenger94** [comment]
Thanks :)
forcing GC works also.
"GC just sees the GtkD object and not the image data it holds because it's on the C heap" 
i understand, but why then GC.collect() sees it ?
i was probably abusing the "leaking" concept from a technical point of view... 
Is what happened here just a common sense memory management case ? i mean don't bother explaining me whole GC concept in D (i'm going to reread about it) but i was surprised and as mentioned `destroy()` (scope(exit) or not) didn't work (at least for me) ...

**Comment by MikeWey** [comment]
> i understand, but why then GC.collect() sees it ?

It doesn't, it just collects the unused Pixbuf object running it's destructor, which in turn frees the pixbuf data.

I'll see if i can find out why destroy crashes.

**Comment by passenger94** [comment]
sorry destroy works indeed in the simple case exposed here, it's in my app viewer where destroying the pixbuf is probably premature in the function where a new pixbuf by means. of scaling, rotating, etc... is needed, so i guess i can't do it there because it must live a little longer.
i'm doing it with `scope(exit) pixbuf.unref()` and all is fine now :-)

Thank you !!!
