### ISSUE TITLE
ListG.toArray

### ISSUE THREAD

**Issue by CromFr** [gtkd-developers/GtkD#129]
https://github.com/gtkd-developers/GtkD/blob/master/src/glib/ListG.d#L100
leading to `Error: undefined identifier 'ListSG'`

`ListSG list = this;` should be set to `auto list = this;` or `ListG list = this;`

**Comment by passenger94** [comment]
probably related :
https://github.com/gtkd-developers/GtkD/blob/master/src/glib/ListSG.d#L104
auto list = new ListG(null); should be **auto list = new ListSG(null);**
