### ISSUE TITLE
LIBRARY.VTE path needs to be updated

### ISSUE THREAD

**Issue by gnunn1** [gtkd-developers/GtkD#135]
I'll preface this by saying I'm not sure if this is an issue with Arch Linux specifically or across all Linux distros. I'm fooling around a bit with the VTE widget, as you probably know they recently changed the VTE ABI from fork_command to spawn_sync. When I try to run the terminal against the default LIBRARY.PATH, libvte2_90.so, I get a complaint about unsatisfied linkage.

If I run nm -D libvte2_90.so, I can see it still has the fork_command function rather then spawn_sync. On Arch Linux, libvte-2.91.so has the spawn_sync command and if I update gtkc.paths.LIBRARY.VTE to use this things work as expected.

**Comment by gnunn1** [comment]
The path was changed to libvte2_91.so but on Arch linux the library is libvte-2.91.so, note the difference in the dash and underscore characters. Is this a specific issue with Arch, in other distros is the library named libvte2_91.so, if so I'll open a bug with Arch. Looking at Debian, it looks like it is using the same naming convention as Arch:

https://packages.debian.org/jessie/amd64/libvte-2.91-0/filelist

**Comment by MikeWey** [comment]
No this one is my fault, i just changed the version number and didn't notice they also switched from a underscore to a dot.
