### ISSUE TITLE
Classes/Structs missing from documentation

### ISSUE THREAD

**Issue by gnunn1** [gtkd-developers/GtkD#136]
I'm not sure if this is an isue with dlang ddocs or by design, but it causes some classes in GtkD to have empty documentation files generated in candydoc. I was trying to generate documentation locally for vte.Terminal and noticed I was getting an empty file. You also see this in other places like glib.Util.

Turns out the problem is that the public class or struct must have a documentation comment in order for the rest of the class/struct to be parsed. So for example, the empty embedded comment below is enough to have ddocs generate things correctly (at least with the default docs, assume it will be same with candydoc).

```
module glib.Util;

private import glib.Str;
private import gtkc.glib;
public  import gtkc.glibtypes;

/** */
public struct Util
{
```

Is it possible to have the code generator insert empty documentation comments for public classes/structs which are missing them so that the documentation gets properly generated in candydoc?

**Comment by MikeWey** [comment]
I just added them for structs and classes, but i still need to check the other cases.

**Comment by gnunn1** [comment]
I haven't noticed anything missing since I opened this bug and you made that commit last year. Feel free to close this issue unless there is something you wanted to follow-up on.
