### ISSUE TITLE
Add constants for style provider priority

### ISSUE THREAD

**Issue by WebFreak001** [gtkd-developers/GtkD#145]
https://developer.gnome.org/gtk3/stable/GtkStyleProvider.html#GTK-STYLE-PROVIDER-PRIORITY-FALLBACK:CAPS

Those are basically used in `StyleContext.addProviderForScreen` and `StyleContext.addProvider` and having constants instead of magic numbers in the code would make it easier to read.

https://github.com/gtkd-developers/GtkD/blob/master/src/gtk/StyleContext.d#L207

Maybe also add another function with an enum instead of uint to make it easier?

**Comment by MikeWey** [comment]
I've added the constants for now.

I tried to generate the constants from the gir files but that creates to many platform/architecture dependant constants, so adding them manually for now.
