### ISSUE TITLE
Clearing accelerators

### ISSUE THREAD

**Issue by gnunn1** [gtkd-developers/GtkD#148]
The Application.setAccelsForAction method has the following in the documentation:

```
To remove all accelerators for an action, use an empty, zero-terminated array for @accels.
```
How do you pass an empty, zero-terminated string array in D since I believe empty arrays in D are treated as null? I'm wondering if I am missing something basic here. I can work around it with the following (probably crap) code but it would be nice to have a D way to do this unless like I said I'm missing something obvious.

```
char** tmp = (new char*[1]).ptr;
tmp[0] = cast(char*) '\0';                
gtkc.gtk.gtk_application_set_accels_for_action(gtkApplication, glib.Str.Str.toStringz(actionName), tmp);
```

**Comment by MikeWey** [comment]
The following might work:
``` D
setAccelsForAction("name", [""]);
```

**Comment by gnunn1** [comment]
Sorry I should have I said I tried that already, it treats the empty as an accelerator and you get the following on stdou with the original accelerator unchanged and activet:

```
(terminix:29802): Gtk-WARNING **: Unable to parse accelerator '': ignored request to install 1 accelerators
```

I also tried an empty array with no luck either.

**Comment by MikeWey** [comment]
I've modified the setAccelsForAction so passing an empty array (or null) removes the accelerators.
