### ISSUE TITLE
Error when compiling with "make all"

### ISSUE THREAD

**Issue by dsboger** [gtkd-developers/GtkD#151]
I get the following error when I try to compile git master with `make all`. I just cloned the repository and called `make all`.

```
Error: unrecognized switch '-Wl,-O1,--sort-common,--as-needed,-z,relro'
GNUmakefile:168: recipe for target 'libgtkd-3.so' failed
```

The failure message is issued when trying to build `libgtkd-3.so`. Am I missing anything? Let me know if I can provide more info.

Thanks!

**Comment by dsboger** [comment]
I managed to properly finish the build with `make LDFLAGS='-L-ldl -m64 -defaultlib=:libphobos2.so' all`. Is that the correct way to do it?

**Comment by MikeWey** [comment]
dmd doesn't understand the LDFLAGS set in the makepkg configuration.

**Comment by dsboger** [comment]
Ok, understood! And here I was trying to figure out where that was coming from... solved clearing LDFLAGS before calling `make all`. Thanks!

**Comment by dsboger** [comment]
I've managed to build and use gtkd together with terminix as a shared library, everything compiled with dmd. Is the following excerpt from REAMDE still true?

```
 * shared          = build gtkd and gtkd-sourceview as shared libraries.
                     This currently only works with LDC.
```

**Comment by MikeWey** [comment]
No, it also works with dmd, not sure about gdc.
