### ISSUE TITLE
Add binding for libpeas & libpeas-gtk

### ISSUE THREAD

**Issue by WebFreak001** [gtkd-developers/GtkD#152]
libpeas is the plugin management system by gnome. They use it basically in all their software to allow extending it.

Adding the package to GtkD (because it relies on glib) would allow people to extend other projects using libpeas but also include a default GTK plugin manager & view using libpeas-gtk.

General project docs: https://developer.gnome.org/libpeas/stable/

**Comment by MikeWey** [comment]
I've added the peas binding, may need some testing.

**Comment by WebFreak001** [comment]
omg that was so quick! gonna test it soon

**Comment by WebFreak001** [comment]
it still needs a sub-configuration in the dub.json

**Comment by MikeWey** [comment]
Added the dub configuration.

**Comment by MikeWey** [comment]
In release 3.4.0
