### ISSUE TITLE
GtkD 3.4.0 Destroy Dialog Assertion Failure

### ISSUE THREAD

**Issue by gnunn1** [gtkd-developers/GtkD#169]
I use the following style of code in Terminix when showing dialogs where a scope(exit) is used tod estroy the dialog:

```
EditTriggersDialog dlg = new EditTriggersDialog(cast(Window) getToplevel(), gsProfile);
scope (exit) {
    dlg.destroy();
}
dlg.showAll();
if (dlg.run() == ResponseType.APPLY) {
    gsProfile.setStrv(SETTINGS_PROFILE_TRIGGERS_KEY, dlg.getTriggers());
}
```

This worked fine in 3.3.0 but in the new 3.4.0 version it seems to be generating an assertion failure in GObject:

```
GLib-GObject:ERROR:gobject.c:2899:toggle_refs_notify: assertion failed: (tstack.n_toggle_refs == 1)
```

It looks to be caused by the unref added in ObjectG.d from this commit, if I comment that out I do not get the assertion failure any longer:

https://github.com/gtkd-developers/GtkD/commit/c62220514133140bfde723fd6d17a46790232d09

That commit was to fix a memory leak I reported in #165.

**Comment by gnunn1** [comment]
I tried changing the ```scope(exit)``` to a try...finally and it didn't make any difference.

**Comment by MikeWey** [comment]
I've changed unref, to properly removing the toggle reference. This should stop GTK from trying to call the toggle callback in the cases where that would no longer be possible.

I can no longer reproduce the issue with this change.

**Comment by gnunn1** [comment]
Thanks @MikeWey that does indeed work fine. Any chance of getting a 3.4.1 release with this change included?

**Comment by MikeWey** [comment]
Done.

**Comment by gnunn1** [comment]
Thanks!
