### ISSUE TITLE
error: GdkQuartzDisplay does not implement the monitor vfuncs

### ISSUE THREAD

**Issue by timotheecour** [gtkd-developers/GtkD#173]
platform:OSX

dub.json contains:
```
"dependencies": {
"ggplotd": "~>1.1.2",
"gtk-d": {"path": "path/to/GtkD" },
},

"subConfigurations": {
"ggplotd": "ggplotd-gtk",
},
```

NOTE: gtk-d contains changes from https://github.com/gtkd-developers/GtkD/pull/172 [that was necessary for OSX]

main.d:
```
void main(){
  import core.thread;
  import ggplotd.ggplotd;
  import ggplotd.gtk;

  const win_width = 1024;
  const win_height = 1024;
  auto gtkwin = new GTKWindow();
  auto tid = new Thread(() { gtkwin.run("plotcli", win_width, win_height); }).start(); 
  auto gg = GGPlotD();
  gtkwin.draw( gg, win_width, win_height );
}
```

```
2017-01-01 22:34:26.532 test_gtkd.exe[48035:26059625] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

(<unknown>:48035): Gdk-WARNING **: GdkQuartzDisplay does not implement the monitor vfuncs
```

**Comment by MikeWey** [comment]
The GdkQuartzDisplay warning is because the Quartz backend doesn't implement all the needed functionality. The warning is generated when gdk_display_get_monitor calls the fallback function.

The first one is also from the Quartz backend.

**Comment by timotheecour** [comment]
I understand it's due to the Quartz backend but would you have any idea how to fix this? (I'm on OSX; same code works fine on ubuntu). It likely affects other OSX users. Any pointers would be appreciated; couldn't find an answer online yet.
NOTE: no window is shown, so this is a blocker

**Comment by MikeWey** [comment]
I don't think those warnings would stop a window from showing up.

Does a simple helloworld[1] application work or does it have the same issues?

[1] https://github.com/gtkd-developers/GtkD/blob/master/demos/gtk/HelloWorld.d

**Comment by timotheecour** [comment]
thanks I tried all demos in demos/gtk they all work [on OSX]
however, the code I was referring to still doesn't work [in fact it crashes after a few seconds]; it works on linux; it's from ggplotd code

**Comment by MikeWey** [comment]
I seem to have the same issue with ggplotd on Linux. It looks link an threading issue.

Modifying the code like this:
```D
void main(){
  import core.thread;
  import ggplotd.ggplotd;
  import ggplotd.gtk;

  const win_width = 1024;
  const win_height = 1024;
  auto gtkwin = new GTKWindow();
  //auto tid = new Thread(() { gtkwin.run("plotcli", win_width, win_height); }).start(); 
  auto gg = GGPlotD();
  gtkwin.draw( gg, win_width, win_height );
  gtkwin.run("plotcli", win_width, win_height);
}
```
I get an window with two axis.

**Comment by MikeWey** [comment]
The fix was merged into ggplotd.
