### ISSUE TITLE
Loader.d: use import core.sys.posix.dlfcn:dlopen etc

### ISSUE THREAD

**Issue by timotheecour** [gtkd-developers/GtkD#174]
i notice Loader.d uses:
```
extern(C){
void* dlopen(char*, int);
}

enum RTLD {...}
```

this is not portable; please use more portable `import core.sys.posix.dlfcn:dlopen` etc

[also, would avoid the ugly cast(char*) in `dlopen(cast(char*)toStringz`

**Comment by MikeWey** [comment]
Should probably do the same for Windows.
