### ISSUE TITLE
cannot build top-level

### ISSUE THREAD

**Issue by timotheecour** [gtkd-developers/GtkD#175]
see https://github.com/dlang/dub/issues/1039#issuecomment-269943187 for reference

**Comment by MikeWey** [comment]
I've changed the target to library, it seems to build only the first sub package.

**Comment by MikeWey** [comment]
I don't use dub that often but the change seems to working for me.

**Comment by timotheecour** [comment]
can we reopen since the fix was reverted?

**Comment by MikeWey** [comment]
Possibly.

I think running `dub build` should build the separate sub projects as separate libraries, and not a single library that has the problems reported in #202.
