### ISSUE TITLE
make:Internal error: backend/go.c 242

### ISSUE THREAD

**Issue by timotheecour** [gtkd-developers/GtkD#176]
```
Internal error: backend/go.c 242
make: *** [demos/gtkD/TestWindow/TestStock.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by MikeWey** [comment]
It's an bug in dmd that is triggered by the demo.
I've disabled the optimizations for dmd to avoid this issue.

https://issues.dlang.org/show_bug.cgi?id=14214

**Comment by timotheecour** [comment]
thanks; that's a rather radical fix ; could this be narrowed down to a single or few files? Also how to make this work within a dub executable target?

The linked bug report shows it happens with a very large cardinality TypeTuple; could we instead fix that?

**Comment by timotheecour** [comment]
https://github.com/gtkd-developers/GtkD/pull/179 fixes this issues and is more efficient.

**Comment by timotheecour** [comment]
after merging #179 could you revert https://github.com/gtkd-developers/GtkD/commit/1d0839eb3e4a06e5074fc8bd090ca099c77b2869 ?
