### ISSUE TITLE
GIO.Socket.Receive not filling string buffer

### ISSUE THREAD

**Issue by ShinRa26** [gtkd-developers/GtkD#178]
When using the GIO.Socket.Receive method to receive data from my server, the data does not fill the string buffer I have set up. E.g.

```d
string buffer = new string(512);
auto recv = client.receive(buffer, null);
writefln("Received %d bytes as: %s", recv, buffer);
```
The print out says I receive the correct amount of bytes but just prints out 512 bytes of emptiness...

Is this a bug in the Socket.receive method or am I missing something here?

**Comment by MikeWey** [comment]
I've corrected the binding for the receive and receiveFrom functions.

The type of the buffer was changed to a char[] since the chars aren't immutable if the function is going to change them.
