### ISSUE TITLE
Makefile: install-headers-peas installs .pc file to wrong path

### ISSUE THREAD

**Issue by dsboger** [gtkd-developers/GtkD#181]
Based on other install-headers-*, the destination path should be `$(DESTDIR)$(prefix)/$(libdir)/pkgconfig`, but it is `$(DESTDIR)$(datadir)/pkgconfig`.

Excerpt from GNUmakefile:
```
install-headers-vte: vted-$(MAJOR).pc install-headers-gtkd
	(cd srcvte; echo $(SOURCES_VTED) | sed -e s,srcvte/,,g | xargs tar cf -) | (cd $(DESTDIR)$(prefix)/include/d/gtkd-$(MAJOR); tar xv)
	install -m 644 vted-$(MAJOR).pc $(DESTDIR)$(prefix)/$(libdir)/pkgconfig

install-headers-peas: peasd-$(MAJOR).pc install-headers-gtkd
	(cd srcpeas; echo $(SOURCES_PEASD) | sed -e s,srcpeas/,,g | xargs tar cf -) | (cd $(DESTDIR)$(prefix)/include/d/gtkd-$(MAJOR); tar xv)
install -m 644 peasd-$(MAJOR).pc $(DESTDIR)$(datadir)/pkgconfig
```

**Comment by MikeWey** [comment]
I think they should all go in the datadir, as per issue #50.
I seems that change was undone in pull #160.

I think they should all be reverted to $(DESTDIR)$(datadir)/pkgconfig

**Comment by dsboger** [comment]
All other files are installed to the right places, but for `peasd-3.pc` it resolves like this:

```
install -m 644 peasd-3.pc /home/build/pkg/gtkd//usr/share/pkgconfig
install: cannot create regular file '/home/build/pkg/gtkd//usr/share/pkgconfig': No such file or directory
```

**Comment by dsboger** [comment]
It is working now, thanks! Would it be possible to release this fix?

**Comment by MikeWey** [comment]
3.5.1 tagged and released.
