### ISSUE TITLE
Illogical method for setting style in gtk converts to illogical binding

### ISSUE THREAD

**Issue by deviator** [gtkd-developers/GtkD#187]
This method [gtk_style_context_add_provider_for_screen](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-style-context-add-provider-for-screen) not use StyleContext but if I want use it in gtkd I must somehow get StyleContext, from widget for example, and if I use Builder for setting style I must pass some widget name, but in core it not necessary. I think this method must be static.

**Comment by MikeWey** [comment]
Do you mean this function:

https://github.com/gtkd-developers/GtkD/blob/master/src/gtk/StyleContext.d#L199

Because it's already static?

**Comment by deviator** [comment]
Oh, sorry)
