### ISSUE TITLE
Subclassing GtkWidget?

### ISSUE THREAD

**Issue by baedert** [gtkd-developers/GtkD#188]
Hi,

is there a way to write a custom widget that inherits from `GtkWidget` directly? iirc I need an actual `GtkWidget *` pointer which is not possible in this case since `GtkWidget` itself is not instantiable.

**Comment by MikeWey** [comment]
Currently that isn't easy, you would have to do the same as you would in C, but you are missing the convenience macro's.

Basically you would have to implement a getType function, that sets an init function for the GtkWidgetClass struct. and in that init function you will need to set the function pointers of the functions you want to override. That function pointer would need to point to a wrapper function that go's from C to D.

If you can wait a while, in implementing a mixin that would do this for you like the one that was recently added for Gtk interfaces: https://github.com/gtkd-developers/GtkD/blob/master/src/gtkd/Implement.d#L30

**Comment by baedert** [comment]
I'm familiar with doing it in C, that's not the problem. Is there any example of how to do this without a mixin? Ifnot, I can wait for it of course, no problem. Thanks.

**Comment by MikeWey** [comment]
The closest example would be how the GtkTreeModel interface is implemented in gtk.TreeModel. https://github.com/gtkd-developers/GtkD/blob/master/src/gtk/TreeModel.d.

In that example the `customTreeModelClassInit` function is where you would set the function pointers.

**Comment by baedert** [comment]
Cool, thanks. Was able to get https://paste.xinu.at/Je8/d working.

**Comment by MikeWey** [comment]
Great, in the mean time the mixin is also added, with still some work left to do.
