### ISSUE TITLE
Trouble with a Gtkd tutorial

### ISSUE THREAD

**Issue by leh103** [gtkd-developers/GtkD#189]
I hope someone can help me with this or maybe its a bug.
The tutorial is a older one based on Gtkd2, but according to the Gtkd3 documentation for PgAttribute.parseMarkup it should work.

// This is the line that the error is in #501
if (PgAttribute.parseMarkup (text, text.length, 0, pgal, plaintext, null))

// This is the error message.
gs6a.d(501): Error: function pango.PgAttribute.PgAttribute.parseMarkup (string mark
upText, int length, dchar accelMarker, out PgAttributeList attrList, out string tex
t, out dchar accelChar) is not callable using argument types (string, ulong, int, P
gAttributeList, string, typeof(null))

I apologize if this is the wrong place to ask, but I have not been able to contact the tutorial author.

**Comment by MikeWey** [comment]
The types of the calls don't match, The sample bellow should work.

```D
dchar dch;
PgAttribute.parseMarkup(text, cast(int)text.length, cast(dchar)'\0', pgal, plaintext, dch);
```

The GtkD newsgroup/forum (http://forum.gtkd.org/) might be a better place to ask these questions, no registration required.

**Comment by leh103** [comment]
Thank you for the help. I will try that out and let you know if it works. I just typed it in as the tutorial specified. I was confused because the the gtkd.org documentation indicated that the original way I had it should work, but it didn't. I will ask for help on the forum the next time I need help.
Again, Thank you for the information.

**Comment by leh103** [comment]
Your information worked except without the / in front of the 0, like so cast(dchar)'0' .
Thought you may like to know.

**Comment by leh103** [comment]
I am going to reclose this now.
