### ISSUE TITLE
gtk.ColorButton setRGBA

### ISSUE THREAD

**Issue by IgnoreAmos** [gtkd-developers/GtkD#191]
Missing a wrapper for void gtk_color_button_set_rgba (GtkColorButton *button,  const GdkRGBA *rgba);

I have been trying to use RGBA since Color has be marked deprecated.  This is a workaround:

gtk_color_button_set_rgba(colourThree.getColorButtonStruct(), new RGBA(r, g, b, a).getRGBAStruct());

**Comment by gnunn1** [comment]
Maybe I'm missing something but ColorButton inherits ```setRgba``` from the interface ```ColorChooserIF```, that should do what you need?

**Comment by IgnoreAmos** [comment]
So it does.  My apologies, it was late and I must have done something wrong. >.<  I should have copied the error message.

Thanks.
