### ISSUE TITLE
"Package gtkglext-3.0 was not found" in "make install..."

### ISSUE THREAD

**Issue by simonbcn** [gtkd-developers/GtkD#196]
Arch Linux

`LDFLAGS='' DC='ldc' make libdir='lib/' shared-libs shared-gstreamer shared-vte shared-peas` all right but when I try to install with 
``` 
$ make prefix='/usr' libdir='lib/' DESTDIR="test/" \
    install-shared install-shared-gstreamer install-shared-vte install-shared-peas \
    install-headers install-headers-gstreamer install-headers-vte install-headers-peas
....
peas/Engine.d
Package gtkglext-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtkglext-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtkglext-3.0' found
```
gtkglext-3.0 isn't installed but it's optional, no?

**Comment by MikeWey** [comment]
Yes, it is optional. There was something wrong with the make file.

The `shared-libs` target also no longer builds the gtkglext binding, it currently builds: gtkd, sourceview, gstreamer, vte and peas. I've also updated the install targets to reflect this.
