### ISSUE TITLE
GApplicationFlags use FLAGS_NONE instead of NONE

### ISSUE THREAD

**Issue by csoriano89** [gtkd-developers/GtkD#197]
So it's inconsistent with the other flags, like GApplicationFlags.HANDLES_COMMAN_LINE which doesn't prefix the FLAGS.

**Comment by MikeWey** [comment]
This is how the enum is defined in the gir files, and in c it is also the only one that contains FLAGS. https://developer.gnome.org/gio/stable/GApplication.html#GApplicationFlags

Although in D you end up with ApplicationFlags.FLAGS_NONE i don't think it's worth it to add an exception to for this enum. And leave is as is the enum member names from C minus there common prefix.

**Comment by csoriano89** [comment]
I promise I triple checked :/ Not sure how I missed this...
Closing
