### ISSUE TITLE
Possibly outdated code in build script

### ISSUE THREAD

**Issue by midchildan** [gtkd-developers/GtkD#199]
Building a shared library of GtkD fails on NixOS, since the build requires a dynamic version of libphobos, while the DMD package in NixOS only seems to provide a static one. But according to a [comment in the Makefile](https://github.com/gtkd-developers/GtkD/blob/master/GNUmakefile#L431-L433), this no longer seems necessary. Could you consider removing it?

**Comment by MikeWey** [comment]
The comment stems from the time that the shared version of phobos was named: `libphobos2so.so` and thus we needed to change the default lib. See also: https://github.com/gtkd-developers/GtkD/commit/7ea7b805c848c5c0c9b5cf6081dd60e187829831

The assumption was that once dlang/phobos/pull/1280 the name would be fixed and ld would default to the shared version, but dmd currently explicitly links the static version so the line remains.

I seem to remember there were issues with using the static version of phobos with shared libraries, but i cant remember the details.

**Comment by midchildan** [comment]
I just encountered the same problem when I tried to link the static version of phobos. I guess I should just build a static library instead. Thanks.
