### ISSUE TITLE
How come no g_signal_connect wrapper?

### ISSUE THREAD

**Issue by Stretto** [gtkd-developers/GtkD#207]
There is a Signals.connectData but no Signals.connect, is there any reason for this?

**Comment by MikeWey** [comment]
It's not wrapped because it's a macro, and not a function.

That means it's not available in the gir files used by the generator, and would need to be added manually. In this case the macro calls g_signal_connect_data with null as the destroyNotify callback.

**Comment by deviator** [comment]
Please add connection to custom signals to widget!

Need for situation like [this](https://stackoverflow.com/questions/29182792/how-to-detect-the-change-of-a-gtkstack-or-gtkstackswitcher).

Temporary workaround, maybe helpful for somebody
```d
import gtk.Widget;
import gdk.Event;
import gobject.ObjectG;
import gobject.Signals;

class CustomSignals
{
    this() {}

    void connect(Widget widget, string signal, bool delegate(Event, Widget) dlg)
    {
        auto wrapper = new Wrapper(widget, dlg);
        Signals.connectData(widget, signal,
                            cast(GCallback)&callback,
                            cast(void*)wrapper,
                            cast(GClosureNotify)&destroyCallback,
                            cast(ConnectFlags)0
                            );
    }

protected:
    class Wrapper
    {
        Widget widget;
        bool delegate(Event, Widget) dlg;

        this(Widget widget, bool delegate(Event, Widget) dlg)
        {
            this.widget = widget;
            this.dlg = dlg;
            wrappers ~= this;
        }

        bool opCall(Event e) { return dlg(e, widget); }

        void selfRemove()
        {
            import std.algorithm : filter;
            import std.array : array;
            wrappers = wrappers.filter!(a => this !is a).array;
        }
    }

    Wrapper[] wrappers;

    extern(C) static int callback(void* widgetStruct, GdkEvent* event, Wrapper wrapper)
    { return wrapper(ObjectG.getDObject!Event(event)); }

    extern(C) static void destroyCallback(Wrapper wrapper, void* closure)
    { wrapper.selfRemove(); }
}
```
Using:
```d
auto csig = new CustomSignals;
csig.connect(myWidget, "some-signal", (Event e, Widget w) { /+ do something +/ });
```

**Comment by MikeWey** [comment]
> Need for situation like [this](https://stackoverflow.com/questions/29182792/how-to-detect-the-change-of-a-gtkstack-or-gtkstackswitcher).

For that example you can use addOnNotify from ObjectG.
```
my_stack.addOnNotify(&vc_changed, "visible-child");
```

For g_signal_connect we should combine it with the DelegatePointer from #137 so it will work with signals that have different parameters then Event and Widget.

**Comment by MikeWey** [comment]
master now has a overload of gobject.Signals.Signals.connect that allows connecting D delegates, functions, or even structs/classes with an 'opCall' defined.

So you could do this for the example above:
```D
Signals.connect(myWidget, "some-signal", (Event e, Widget w) { /+ do something +/ });
```
