### ISSUE TITLE
Library load failed on windows

### ISSUE THREAD

**Issue by KytoDragon** [gtkd-developers/GtkD#208]
I am trying to build an aplication using GtkD but keep getting the following error during start up:
object.Exception@..\..\..\generated\gtkd\gtkd\Loader.d(125): Library load failed (libglib-2.0-0.dll):  is not a valid win32 application.

Gtk runtime version 3.8.1 is installed. Also, i have no problem loading the library myself using LoadLibraryA (getting a non-null handle) as "C:\Program Files (x86)\gtk-3.8.1" is in my path (and the value of GTK_BASEPATH).

I am building using dub and LDC with either a x32 or a x64 target on Windows 7 x64.
This happen with all of the demo programms.
I have already tried using different versions of Gtk (older ones as well as newly compiled using mingw).

**Comment by MikeWey** [comment]
> I am trying to build an aplication using GtkD but keep getting the following error during start up:
> object.Exception@......\generated\gtkd\gtkd\Loader.d(125): Library load failed (libglib-2.0-0.dll): is not a valid win32 application.

The `is not a valid win32 application.` part is the error message from `LoadLibrary` and i think that would mean an 32/64 bit mismatch.

> Gtk runtime version 3.8.1 is installed. Also, i have no problem loading the library myself using LoadLibraryA (getting a non-null handle) as "C:\Program Files (x86)\gtk-3.8.1" is in my path (and the value of GTK_BASEPATH).

GtkD currently doesn't use the `GTK_BASEPATH` environment variable, it only checks the path.
The directory in the path would need to contain the gtk libraries, this would usually be `C:\Program Files (x86)\gtk-3.8.1\bin`.

Also where are you getting your copy of GTK? 3.8 is fairly old, an installer for 3.22 is available on gtkd.org.

> I am building using dub and LDC with either a x32 or a x64 target on Windows 7 x64.
> This happen with all of the demo programms.
> I have already tried using different versions of Gtk (older ones as well as newly compiled using mingw).

**Comment by KytoDragon** [comment]
Version 3.8 was the newest version I could find as binaries via google, as the official site (gtk.org) only supplied outdated installation intructions. I have now replaced my version with the one at gtkd.org and get the following:
`Loaded lib = libgio-2.0-0.dll
Loaded lib = libgobject-2.0-0.dll
Loaded lib = libgdk_pixbuf-2.0-0.dll
Loaded lib = libglib-2.0-0.dll
Loaded lib = libpango-1.0-0.dll
Loaded lib = libgdk-3-0.dll
Loaded lib = libatk-1.0-0.dll
Loaded lib = libgtk-3-0.dll
Loaded lib = libcairo-2.dll
Loaded lib = libgmodule-2.0-0.dll
Loaded lib = libpangocairo-1.0-0.dll
failed (libgio-2.0-0.dll) g_credentials_get_unix_pid
failed (libgio-2.0-0.dll) g_credentials_get_unix_user
failed (libgio-2.0-0.dll) g_credentials_set_unix_user
failed (libgio-2.0-0.dll) g_dbus_connection_call_with_unix_fd_list
failed (libgio-2.0-0.dll) g_dbus_connection_call_with_unix_fd_list_finish
failed (libgio-2.0-0.dll) g_dbus_connection_call_with_unix_fd_list_sync
failed (libgio-2.0-0.dll) g_dbus_message_get_unix_fd_list
failed (libgio-2.0-0.dll) g_dbus_message_set_unix_fd_list
failed (libgio-2.0-0.dll) g_dbus_method_invocation_return_value_with_unix_fd_list
failed (libgio-2.0-0.dll) g_dbus_proxy_call_with_unix_fd_list
failed (libgio-2.0-0.dll) g_dbus_proxy_call_with_unix_fd_list_finish
failed (libgio-2.0-0.dll) g_dbus_proxy_call_with_unix_fd_list_sync
failed (libgio-2.0-0.dll) g_desktop_app_info_get_type
failed (libgio-2.0-0.dll) g_desktop_app_info_new
failed (libgio-2.0-0.dll) g_desktop_app_info_new_from_filename
failed (libgio-2.0-0.dll) g_desktop_app_info_new_from_keyfile
failed (libgio-2.0-0.dll) g_desktop_app_info_get_implementations
failed (libgio-2.0-0.dll) g_desktop_app_info_search
failed (libgio-2.0-0.dll) g_desktop_app_info_set_desktop_env
failed (libgio-2.0-0.dll) g_desktop_app_info_get_action_name
failed (libgio-2.0-0.dll) g_desktop_app_info_get_boolean
failed (libgio-2.0-0.dll) g_desktop_app_info_get_categories
failed (libgio-2.0-0.dll) g_desktop_app_info_get_filename
failed (libgio-2.0-0.dll) g_desktop_app_info_get_generic_name
failed (libgio-2.0-0.dll) g_desktop_app_info_get_is_hidden
failed (libgio-2.0-0.dll) g_desktop_app_info_get_keywords
failed (libgio-2.0-0.dll) g_desktop_app_info_get_nodisplay
failed (libgio-2.0-0.dll) g_desktop_app_info_get_show_in
failed (libgio-2.0-0.dll) g_desktop_app_info_get_startup_wm_class
failed (libgio-2.0-0.dll) g_desktop_app_info_get_string
failed (libgio-2.0-0.dll) g_desktop_app_info_has_key
failed (libgio-2.0-0.dll) g_desktop_app_info_launch_action
failed (libgio-2.0-0.dll) g_desktop_app_info_launch_uris_as_manager
failed (libgio-2.0-0.dll) g_desktop_app_info_list_actions
failed (libgio-2.0-0.dll) g_desktop_app_info_lookup_get_type
failed (libgio-2.0-0.dll) g_desktop_app_info_lookup_get_default_for_uri_scheme
failed (libgio-2.0-0.dll) g_file_descriptor_based_get_type
failed (libgio-2.0-0.dll) g_file_descriptor_based_get_fd
failed (libgio-2.0-0.dll) g_subprocess_send_signal
failed (libgio-2.0-0.dll) g_subprocess_launcher_set_child_setup
failed (libgio-2.0-0.dll) g_subprocess_launcher_set_stderr_file_path
failed (libgio-2.0-0.dll) g_subprocess_launcher_set_stdin_file_path
failed (libgio-2.0-0.dll) g_subprocess_launcher_set_stdout_file_path
failed (libgio-2.0-0.dll) g_subprocess_launcher_take_fd
failed (libgio-2.0-0.dll) g_subprocess_launcher_take_stderr_fd
failed (libgio-2.0-0.dll) g_subprocess_launcher_take_stdin_fd
failed (libgio-2.0-0.dll) g_subprocess_launcher_take_stdout_fd
failed (libgio-2.0-0.dll) g_unix_connection_get_type
failed (libgio-2.0-0.dll) g_unix_connection_receive_credentials
failed (libgio-2.0-0.dll) g_unix_connection_receive_credentials_async
failed (libgio-2.0-0.dll) g_unix_connection_receive_credentials_finish
failed (libgio-2.0-0.dll) g_unix_connection_receive_fd
failed (libgio-2.0-0.dll) g_unix_connection_send_credentials
failed (libgio-2.0-0.dll) g_unix_connection_send_credentials_async
failed (libgio-2.0-0.dll) g_unix_connection_send_credentials_finish
failed (libgio-2.0-0.dll) g_unix_connection_send_fd
failed (libgio-2.0-0.dll) g_unix_credentials_message_get_type
failed (libgio-2.0-0.dll) g_unix_credentials_message_new
failed (libgio-2.0-0.dll) g_unix_credentials_message_new_with_credentials
failed (libgio-2.0-0.dll) g_unix_credentials_message_is_supported
failed (libgio-2.0-0.dll) g_unix_credentials_message_get_credentials
failed (libgio-2.0-0.dll) g_unix_fd_list_get_type
failed (libgio-2.0-0.dll) g_unix_fd_list_new
failed (libgio-2.0-0.dll) g_unix_fd_list_new_from_array
failed (libgio-2.0-0.dll) g_unix_fd_list_append
failed (libgio-2.0-0.dll) g_unix_fd_list_get
failed (libgio-2.0-0.dll) g_unix_fd_list_get_length
failed (libgio-2.0-0.dll) g_unix_fd_list_peek_fds
failed (libgio-2.0-0.dll) g_unix_fd_list_steal_fds
failed (libgio-2.0-0.dll) g_unix_fd_message_get_type
failed (libgio-2.0-0.dll) g_unix_fd_message_new
failed (libgio-2.0-0.dll) g_unix_fd_message_new_with_fd_list
failed (libgio-2.0-0.dll) g_unix_fd_message_append_fd
failed (libgio-2.0-0.dll) g_unix_fd_message_get_fd_list
failed (libgio-2.0-0.dll) g_unix_fd_message_steal_fds
failed (libgio-2.0-0.dll) g_unix_input_stream_get_type
failed (libgio-2.0-0.dll) g_unix_input_stream_new
failed (libgio-2.0-0.dll) g_unix_input_stream_get_close_fd
failed (libgio-2.0-0.dll) g_unix_input_stream_get_fd
failed (libgio-2.0-0.dll) g_unix_input_stream_set_close_fd
failed (libgio-2.0-0.dll) g_unix_is_mount_path_system_internal
failed (libgio-2.0-0.dll) g_unix_mount_at
failed (libgio-2.0-0.dll) g_unix_mount_compare
failed (libgio-2.0-0.dll) g_unix_mount_free
failed (libgio-2.0-0.dll) g_unix_mount_get_device_path
failed (libgio-2.0-0.dll) g_unix_mount_get_fs_type
failed (libgio-2.0-0.dll) g_unix_mount_get_mount_path
failed (libgio-2.0-0.dll) g_unix_mount_guess_can_eject
failed (libgio-2.0-0.dll) g_unix_mount_guess_icon
failed (libgio-2.0-0.dll) g_unix_mount_guess_name
failed (libgio-2.0-0.dll) g_unix_mount_guess_should_display
failed (libgio-2.0-0.dll) g_unix_mount_guess_symbolic_icon
failed (libgio-2.0-0.dll) g_unix_mount_is_readonly
failed (libgio-2.0-0.dll) g_unix_mount_is_system_internal
failed (libgio-2.0-0.dll) g_unix_mount_points_changed_since
failed (libgio-2.0-0.dll) g_unix_mount_points_get
failed (libgio-2.0-0.dll) g_unix_mounts_changed_since
failed (libgio-2.0-0.dll) g_unix_mounts_get
failed (libgio-2.0-0.dll) g_unix_mount_monitor_get_type
failed (libgio-2.0-0.dll) g_unix_mount_monitor_new
failed (libgio-2.0-0.dll) g_unix_mount_monitor_get
failed (libgio-2.0-0.dll) g_unix_mount_monitor_set_rate_limit
failed (libgio-2.0-0.dll) g_unix_mount_point_compare
failed (libgio-2.0-0.dll) g_unix_mount_point_free
failed (libgio-2.0-0.dll) g_unix_mount_point_get_device_path
failed (libgio-2.0-0.dll) g_unix_mount_point_get_fs_type
failed (libgio-2.0-0.dll) g_unix_mount_point_get_mount_path
failed (libgio-2.0-0.dll) g_unix_mount_point_get_options
failed (libgio-2.0-0.dll) g_unix_mount_point_guess_can_eject
failed (libgio-2.0-0.dll) g_unix_mount_point_guess_icon
failed (libgio-2.0-0.dll) g_unix_mount_point_guess_name
failed (libgio-2.0-0.dll) g_unix_mount_point_guess_symbolic_icon
failed (libgio-2.0-0.dll) g_unix_mount_point_is_loopback
failed (libgio-2.0-0.dll) g_unix_mount_point_is_readonly
failed (libgio-2.0-0.dll) g_unix_mount_point_is_user_mountable
failed (libgio-2.0-0.dll) g_unix_output_stream_get_type
failed (libgio-2.0-0.dll) g_unix_output_stream_new
failed (libgio-2.0-0.dll) g_unix_output_stream_get_close_fd
failed (libgio-2.0-0.dll) g_unix_output_stream_get_fd
failed (libgio-2.0-0.dll) g_unix_output_stream_set_close_fd
failed (libgio-2.0-0.dll) g_unix_socket_address_get_type
failed (libgio-2.0-0.dll) g_unix_socket_address_new
failed (libgio-2.0-0.dll) g_unix_socket_address_new_abstract
failed (libgio-2.0-0.dll) g_unix_socket_address_new_with_type
failed (libgio-2.0-0.dll) g_unix_socket_address_abstract_names_supported
failed (libgio-2.0-0.dll) g_unix_socket_address_get_address_type
failed (libgio-2.0-0.dll) g_unix_socket_address_get_is_abstract
failed (libgio-2.0-0.dll) g_unix_socket_address_get_path
failed (libgio-2.0-0.dll) g_unix_socket_address_get_path_len
failed (libgio-2.0-0.dll) g_content_type_is_mime_type
failed (libgobject-2.0-0.dll) g_dir_read_name
failed (libgobject-2.0-0.dll) g_dir_open
failed (libgobject-2.0-0.dll) g_io_channel_new_file
failed (libgobject-2.0-0.dll) g_source_add_unix_fd
failed (libgobject-2.0-0.dll) g_source_modify_unix_fd
failed (libgobject-2.0-0.dll) g_source_query_unix_fd
failed (libgobject-2.0-0.dll) g_source_remove_unix_fd
failed (libgobject-2.0-0.dll) g_module_name
failed (libgobject-2.0-0.dll) g_module_open
failed (libgobject-2.0-0.dll) g_spawn_async
failed (libgobject-2.0-0.dll) g_spawn_async_with_pipes
failed (libgobject-2.0-0.dll) g_spawn_command_line_async
failed (libgobject-2.0-0.dll) g_spawn_command_line_sync
failed (libgobject-2.0-0.dll) g_spawn_sync
failed (libgobject-2.0-0.dll) g_get_current_dir
failed (libgobject-2.0-0.dll) g_getenv
failed (libgobject-2.0-0.dll) g_setenv
failed (libgobject-2.0-0.dll) g_unsetenv
failed (libgobject-2.0-0.dll) g_filename_from_utf8
failed (libgobject-2.0-0.dll) g_filename_to_utf8
failed (libgobject-2.0-0.dll) g_file_get_contents
failed (libgobject-2.0-0.dll) g_file_open_tmp
failed (libgobject-2.0-0.dll) g_file_test
failed (libgobject-2.0-0.dll) g_mkstemp
failed (libgobject-2.0-0.dll) g_utf8_make_valid
failed (libgobject-2.0-0.dll) g_unix_error_quark
failed (libgobject-2.0-0.dll) g_unix_fd_add
failed (libgobject-2.0-0.dll) g_unix_fd_add_full
failed (libgobject-2.0-0.dll) g_unix_fd_source_new
failed (libgobject-2.0-0.dll) g_unix_open_pipe
failed (libgobject-2.0-0.dll) g_unix_set_fd_nonblocking
failed (libgobject-2.0-0.dll) g_unix_signal_add
failed (libgobject-2.0-0.dll) g_unix_signal_add_full
failed (libgobject-2.0-0.dll) g_unix_signal_source_new
failed (libgobject-2.0-0.dll) g_filename_from_uri
failed (libgobject-2.0-0.dll) g_filename_to_uri
failed (libgobject-2.0-0.dll) g_uuid_string_is_valid
failed (libgobject-2.0-0.dll) g_uuid_string_random
failed (libgobject-2.0-0.dll) g_module_name_uft8
failed (libgdk_pixbuf-2.0-0.dll) gdk_pixbuf_save
failed (libglib-2.0-0.dll) g_dir_read_name
failed (libglib-2.0-0.dll) g_dir_open
failed (libglib-2.0-0.dll) g_io_channel_new_file
failed (libglib-2.0-0.dll) g_source_add_unix_fd
failed (libglib-2.0-0.dll) g_source_modify_unix_fd
failed (libglib-2.0-0.dll) g_source_query_unix_fd
failed (libglib-2.0-0.dll) g_source_remove_unix_fd
failed (libglib-2.0-0.dll) g_module_name
failed (libglib-2.0-0.dll) g_module_open
failed (libglib-2.0-0.dll) g_spawn_async
failed (libglib-2.0-0.dll) g_spawn_async_with_pipes
failed (libglib-2.0-0.dll) g_spawn_command_line_async
failed (libglib-2.0-0.dll) g_spawn_command_line_sync
failed (libglib-2.0-0.dll) g_spawn_sync
failed (libglib-2.0-0.dll) g_get_current_dir
failed (libglib-2.0-0.dll) g_getenv
failed (libglib-2.0-0.dll) g_setenv
failed (libglib-2.0-0.dll) g_unsetenv
failed (libglib-2.0-0.dll) g_filename_from_utf8
failed (libglib-2.0-0.dll) g_filename_to_utf8
failed (libglib-2.0-0.dll) g_file_get_contents
failed (libglib-2.0-0.dll) g_file_open_tmp
failed (libglib-2.0-0.dll) g_file_test
failed (libglib-2.0-0.dll) g_mkstemp
failed (libglib-2.0-0.dll) g_utf8_make_valid
failed (libglib-2.0-0.dll) g_unix_error_quark
failed (libglib-2.0-0.dll) g_unix_fd_add
failed (libglib-2.0-0.dll) g_unix_fd_add_full
failed (libglib-2.0-0.dll) g_unix_fd_source_new
failed (libglib-2.0-0.dll) g_unix_open_pipe
failed (libglib-2.0-0.dll) g_unix_set_fd_nonblocking
failed (libglib-2.0-0.dll) g_unix_signal_add
failed (libglib-2.0-0.dll) g_unix_signal_add_full
failed (libglib-2.0-0.dll) g_unix_signal_source_new
failed (libglib-2.0-0.dll) g_filename_from_uri
failed (libglib-2.0-0.dll) g_filename_to_uri
failed (libglib-2.0-0.dll) g_uuid_string_is_valid
failed (libglib-2.0-0.dll) g_uuid_string_random
failed (libglib-2.0-0.dll) g_module_name_uft8
failed (libgdk-3-0.dll) gdk_x11_window_get_type
failed (libgdk-3-0.dll) gdk_x11_window_foreign_new_for_display
failed (libgdk-3-0.dll) gdk_x11_window_lookup_for_display
failed (libgdk-3-0.dll) gdk_x11_window_get_desktop
failed (libgdk-3-0.dll) gdk_x11_window_get_xid
failed (libgdk-3-0.dll) gdk_x11_window_move_to_current_desktop
failed (libgdk-3-0.dll) gdk_x11_window_move_to_desktop
failed (libgdk-3-0.dll) gdk_x11_window_set_frame_extents
failed (libgdk-3-0.dll) gdk_x11_window_set_frame_sync_enabled
failed (libgdk-3-0.dll) gdk_x11_window_set_hide_titlebar_when_maximized
failed (libgdk-3-0.dll) gdk_x11_window_set_theme_variant
failed (libgdk-3-0.dll) gdk_x11_window_set_user_time
failed (libgdk-3-0.dll) gdk_x11_window_set_utf8_property
failed (libgdk-3-0.dll) gtk_flow_box_get_child_at_pos
failed (libgdk-3-0.dll) gtk_plug_get_type
failed (libgdk-3-0.dll) gtk_plug_new
failed (libgdk-3-0.dll) gtk_plug_new_for_display
failed (libgdk-3-0.dll) gtk_plug_construct
failed (libgdk-3-0.dll) gtk_plug_construct_for_display
failed (libgdk-3-0.dll) gtk_plug_get_embedded
failed (libgdk-3-0.dll) gtk_plug_get_id
failed (libgdk-3-0.dll) gtk_plug_get_socket_window
failed (libgdk-3-0.dll) gtk_socket_get_type
failed (libgdk-3-0.dll) gtk_socket_new
failed (libgdk-3-0.dll) gtk_socket_add_id
failed (libgdk-3-0.dll) gtk_socket_get_id
failed (libgdk-3-0.dll) gtk_socket_get_plug_window
failed (libgtk-3-0.dll) gtk_flow_box_get_child_at_pos
failed (libgtk-3-0.dll) gtk_plug_get_type
failed (libgtk-3-0.dll) gtk_plug_new
failed (libgtk-3-0.dll) gtk_plug_new_for_display
failed (libgtk-3-0.dll) gtk_plug_construct
failed (libgtk-3-0.dll) gtk_plug_construct_for_display
failed (libgtk-3-0.dll) gtk_plug_get_embedded
failed (libgtk-3-0.dll) gtk_plug_get_id
failed (libgtk-3-0.dll) gtk_plug_get_socket_window
failed (libgtk-3-0.dll) gtk_socket_get_type
failed (libgtk-3-0.dll) gtk_socket_new
failed (libgtk-3-0.dll) gtk_socket_add_id
failed (libgtk-3-0.dll) gtk_socket_get_id
failed (libgtk-3-0.dll) gtk_socket_get_plug_window
failed (libgmodule-2.0-0.dll) g_dir_read_name
failed (libgmodule-2.0-0.dll) g_dir_open
failed (libgmodule-2.0-0.dll) g_io_channel_new_file
failed (libgmodule-2.0-0.dll) g_source_add_unix_fd
failed (libgmodule-2.0-0.dll) g_source_modify_unix_fd
failed (libgmodule-2.0-0.dll) g_source_query_unix_fd
failed (libgmodule-2.0-0.dll) g_source_remove_unix_fd
failed (libgmodule-2.0-0.dll) g_module_name
failed (libgmodule-2.0-0.dll) g_module_open
failed (libgmodule-2.0-0.dll) g_spawn_async
failed (libgmodule-2.0-0.dll) g_spawn_async_with_pipes
failed (libgmodule-2.0-0.dll) g_spawn_command_line_async
failed (libgmodule-2.0-0.dll) g_spawn_command_line_sync
failed (libgmodule-2.0-0.dll) g_spawn_sync
failed (libgmodule-2.0-0.dll) g_get_current_dir
failed (libgmodule-2.0-0.dll) g_getenv
failed (libgmodule-2.0-0.dll) g_setenv
failed (libgmodule-2.0-0.dll) g_unsetenv
failed (libgmodule-2.0-0.dll) g_filename_from_utf8
failed (libgmodule-2.0-0.dll) g_filename_to_utf8
failed (libgmodule-2.0-0.dll) g_file_get_contents
failed (libgmodule-2.0-0.dll) g_file_open_tmp
failed (libgmodule-2.0-0.dll) g_file_test
failed (libgmodule-2.0-0.dll) g_mkstemp
failed (libgmodule-2.0-0.dll) g_utf8_make_valid
failed (libgmodule-2.0-0.dll) g_unix_error_quark
failed (libgmodule-2.0-0.dll) g_unix_fd_add
failed (libgmodule-2.0-0.dll) g_unix_fd_add_full
failed (libgmodule-2.0-0.dll) g_unix_fd_source_new
failed (libgmodule-2.0-0.dll) g_unix_open_pipe
failed (libgmodule-2.0-0.dll) g_unix_set_fd_nonblocking
failed (libgmodule-2.0-0.dll) g_unix_signal_add
failed (libgmodule-2.0-0.dll) g_unix_signal_add_full
failed (libgmodule-2.0-0.dll) g_unix_signal_source_new
failed (libgmodule-2.0-0.dll) g_filename_from_uri
failed (libgmodule-2.0-0.dll) g_filename_to_uri
failed (libgmodule-2.0-0.dll) g_uuid_string_is_valid
failed (libgmodule-2.0-0.dll) g_uuid_string_random
failed (libgmodule-2.0-0.dll) g_module_name_uft8`

For now all the demo application seem to work fine though...

**Comment by MikeWey** [comment]
There is one demo, `TestWindow` that explicitly prints this list. On Windows this list will contain a lot of unix/linux only functions.

https://github.com/gtkd-developers/GtkD/blob/master/demos/gtkD/TestWindow/TestWindow.d#L976

The windows instructions on gtk.org don't look outdated to me, the installer on gtkd.org is actually build using the binaries from msys2.

**Comment by KytoDragon** [comment]
For everyone having similar problems to mine:
It seems that the packages distributed via the pacman package manager (as explained on gtk.org) are sometimes broken (e.q. gdk-pixbuf has a broken dll) or outdated (e.q. gtk-sourceview is only at version 3.20). You can find newer versions at:
`https://sourceforge.net/projects/msys2/files/REPOS/MINGW/`
