### ISSUE TITLE
Widgets no longer being freed after 3.5.1

### ISSUE THREAD

**Issue by gnunn1** [gtkd-developers/GtkD#211]
In Tilix I've added some code ages ago to various high level widget destructors that outputs whether the destructor is called or not. I should be paying more attention to this on GtkD version updates, however I was looking into memory usage recently and noticed a change in behavior starting with 3.6.0.

In 3.5.1 if I close a tiled terminal then execute a GC collection a couple of times I can see the various destructors (VTE, Terminal) being called as expected. However starting in 3.6.0 this no longer happens and the destructors are not called until the program terminates. Now I know that in D destructors are not guarenteed to be called but I use this as a rough barometer with regards to whether I'm leaking objects.

Looking at the changes made between the two versions, there is one thing that sticks out to me. In commit 4b491f5c0d7b60f036900b3f49435caac4f18f9c, the event listeners array were changed from being class members to static members of the wrapper. I was wondering if this could be causing a reference to the delegate being held onto to since it never gets removed from the static unless explicitly removed.

**Comment by MikeWey** [comment]
I think that is indeed the problem.

**Comment by gnunn1** [comment]
I see you made some commits, not sure if it's ready for testing but I gave it a shot by building tilix against GtkD master. Unfortunately, no change as I still see the same behavior from the 3.6.x series though I can see the static listener array has been removed.

I'll do some more digging on my end, if you want to try tilix yourself to see the issue I can post the steps I'm using to build and reproduce it.

**Comment by MikeWey** [comment]
> I'll do some more digging on my end, if you want to try tilix yourself to see the issue I can post the steps I'm using to build and reproduce it.

Yes, could you post the steps to reproduce the issue.

**Comment by gnunn1** [comment]
* Update dub.json and dub.selections.json to 3.5.1

* Compile tilix using ```dub build --build=debug --config=trace```

* If you don't have tilix installed, you will need to do via ```sudo ./install.sh```

* Run tilix from another terminal, you should see a bunch of trace logged to stdout

* In Tilix split a terminal using one of the buttons in the header bar

* Close the new terminal by pressing it's close button

* In the hamburger menu in the header bar click the GC option. You should see something like ```*** VTE Destructor```

* Click GC again and you should see ```*** Terminal destructor````

* Close tilix and compile it with 3.6.5. Repeat the steps above, no destructors are logged until you close tilix.

**Comment by gnunn1** [comment]
Did all have the listeners get re-generated properly in master after that last commit, I'm still seeing some declared as static:

```
grep -R "static.*listeners" *
gtkd/gobject/ObjectG.d:		static OnNotifyDelegateWrapper[] listeners;
gtkd/gtk/Widget.d:			static ScopedOnDrawDelegateWrapper[] listeners;
gtkd/gtk/Widget.d:			static OnDrawDelegateWrapper[] listeners;
gtkd/gtk/ComboBoxText.d:		static OnChangedDelegateWrapper[] listeners;
gtkd/gtk/ComboBoxText.d:		static OnFormatEntryTextDelegateWrapper[] listeners;
gtkd/gtk/ComboBoxText.d:		static OnMoveActiveDelegateWrapper[] listeners;
gtkd/gtk/ComboBoxText.d:		static OnPopdownDelegateWrapper[] listeners;
gtkd/gtk/ComboBoxText.d:		static OnPopupDelegateWrapper[] listeners;
gtkd/gio/Application.d:		static ScopedOnCommandLineDelegateWrapper[] listeners;
```

**Comment by gnunn1** [comment]
My memory is returning, those are the hand written ones if I remember correctly. I'll comment out the places I'm using those and test again.

**Comment by gnunn1** [comment]
Once I comment out my onDraw handlers everything works as expected so the change of listeners to static is definitely the issue.

**Comment by MikeWey** [comment]
I've fixed the manually added signals, and tagged version 3.6.6.

**Comment by gnunn1** [comment]
Thanks @MikeWey, works great.
