### ISSUE TITLE
Incorrectly spelled method name in TreeModelIF.d

### ISSUE THREAD

**Issue by Racinettee** [gtkd-developers/GtkD#212]
In TreeModelIF.d on line 288 the `foreach` method is spelled `foreac`

**Comment by MikeWey** [comment]
As you may have found out, `foreach` is a keyword so it can't be used.

GtkD drops the last character to get around this, an other option would have been to pre of postfix an underscore.

**Comment by Racinettee** [comment]
I had a short lapse regarding the existence or a foreach keyword, sorry.
