### ISSUE TITLE
Missing Constants?

### ISSUE THREAD

**Issue by pokedpeter** [gtkd-developers/GtkD#213]
I am trying to figure out how to add constants, in particular for a first go: Gtk.STYLE_CLASS_LINKED. For starters, Is it even possible to add this?

**Comment by MikeWey** [comment]
The generator currently doesn't generate the constants, tough we should be able to add this.

**Comment by pokedpeter** [comment]
Sorry Mike, how can I access these constants? I've trying a few things but only seem to have access to the public enums in that file.

Thanks for the quick response and fix btw!

**Comment by MikeWey** [comment]
The *.c.types modules are publicly imported by the modules of the parent package.

So if you import any of the gtk modules you should be able to use `STYLE_CLASS_LINKED` or `GTK_STYLE_CLASS_LINKED` without importing anything else.
