### ISSUE TITLE
Add appsink api

### ISSUE THREAD

**Issue by InfiniteRegression** [gtkd-developers/GtkD#215]
Would it be possible to get the appsink api added?

https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-appsink.html

https://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/gst-plugins-base-plugins-0.10/gst-plugins-base-plugins-appsink.html

**Comment by MikeWey** [comment]
I'll have to take a closer look, but technically if it is in the introspection files it would be easy to add.
