### ISSUE TITLE
DClosure implementation

### ISSUE THREAD

**Issue by dhasenan** [gtkd-developers/GtkD#225]
There are a number of API functions that accept a `gobject.Closure` and don't accept a function/callback pair. For example, `gtk.AccelGroup.AccelGroup.connect`. A few problems with this:

* D's type system doesn't let me use `gobject.CClosure` in these locations.
* The natural way to write these in D is with a delegate. This isn't an option here.
* I can't access parameters with a `gobject.CClosure` in any obvious way.
* I have to cast from eg `void function(void* context)` to `void function()`, which is not type-safe.

It would be great to add a way to create an appropriate `Closure` object.

**Comment by MikeWey** [comment]
It look like we need to implement a marshal function to translate an array of GValues into a D function/delegate call. And add a DClosure to hold the function pointer/delegate.
