### ISSUE TITLE
support for dstring

### ISSUE THREAD

**Issue by aitzkora** [gtkd-developers/GtkD#227]
Hi,
When I look at the signature of gtk_label_set_text, it seems that it uses a const gchar * as a parameter. Maybe I wrong but it seems that setText methods use only strings as parameters. How I could handle utf8 strings ? If you have any ideas, it would be nice
Best regards

**Comment by MikeWey** [comment]
dStrings are in utf32, both D and gtk use utf8 most of the time.

To pass a dstring use `std.utf.toUtf8`.

**Comment by aitzkora** [comment]
Indeed, it solves the problem using std.utf.toUTF8.
Thanks a lot, your could close this issue
Bests regards,
