### ISSUE TITLE
Issue with D 2.079

### ISSUE THREAD

**Issue by the-Mitu** [gtkd-developers/GtkD#230]
Hello,

I've recently tried to use GtkD with the DMD 2.079 RC.

However, compiler yields an error from GtkD:

    ../../.dub/packages/gtk-d-3.7.3/gtk-d/generated/gtkd/gtk/Widget.d(7882,25): Error: function `gtk.Widget.Widget.callBackDestroy(OnDelegateWrapper wrapper, GClosure* closure)` cannot be overloaded with another `extern(C)` function at ../../.dub/packages/gtk-d-3.7.3/gtk-d/generated/gtkd/gtk/Widget.d(6858,25)
    /usr/bin/dmd failed with exit code 1.

**Comment by MikeWey** [comment]
This was fixed in the 'GtkD-3.7' branch and in master. I just need to tag the next release.

**Comment by MikeWey** [comment]
GtkD 3.7.4 is taged and released. Which includes the fix for this issue.

**Comment by the-Mitu** [comment]
Wow, that was quick. Thank you! :)
