### ISSUE TITLE
OSX: `make all` fails with: ld: unknown option: -soname=libgtkd-3.so.0

### ISSUE THREAD

**Issue by timotheecour** [gtkd-developers/GtkD#233]
README.md says: `The build options are the same as for Linux.` but looks like there are linux specific things, and make all fails with `ld: unknown option: -soname=libgtkd-3.so.0`

**Comment by MikeWey** [comment]
The current make file also builds the shared libraries as `libgtkd-3.so.0.7.5` that whould probably also need to change to `libgtkd-3.0.dylib` yes ?

So something like this in stead of -soname:
```
-install_name="libgtkd.3.0.dylib" -current_version 3.7.5 -compatibility_version 3.0
```

**Comment by timotheecour** [comment]
indeed...

**Comment by timotheecour** [comment]
side question: readme mentions OSX should build via `make all` but could we also add instructions via dub? (especially since it's not trivial as `dub build` doesn't work, see https://github.com/gtkd-developers/GtkD/issues/175)

**Comment by MikeWey** [comment]
I've updated the make file so it uses 'dylib' and '-install_name'.

**Comment by MikeWey** [comment]
Is seems the flags i used are actually for libtool, i've switched then for the flags found in the OSX man page of ld.

**Comment by timotheecour** [comment]
https://github.com/gtkd-developers/GtkD/pull/234/files
