### ISSUE TITLE
Release Update for Gnome 3.28

### ISSUE THREAD

**Issue by gnunn1** [gtkd-developers/GtkD#236]
Gnome 3.28 is upon us and it adds some new features. For tilix there were a few new features added to the VTE such as background paint operator, blink mode and scaling features that I would like to push out to users that require a release and update of GtkD.

Note there is no huge urgency for this update, whenever you have time. Just opening an issue to track it.

**Comment by MikeWey** [comment]
Done.

Note that the Terminal.feedChild function is properly annotated on the C side now, so it no longer has a separate length parameter.

**Comment by gnunn1** [comment]
Thanks @MikeWey, I have updated tilix in git to use this new version and enabled the new VTE features as a result. Much appreciated as always.
