### ISSUE TITLE
Is "public void foreac" a typo in TreeModelIF.d

### ISSUE THREAD

**Issue by mywtfmp3** [gtkd-developers/GtkD#243]
```d
public void foreac(GtkTreeModelForeachFunc func, void* userData);
```

https://github.com/gtkd-developers/GtkD/blob/master/generated/gtkd/gtk/TreeModelIF.d#L295

Or because `foreach` is already a keyword in D?

**Comment by MikeWey** [comment]
It's because foreach is a keyword, you will see the same thing for a few other functions that are also D keywords.

**Comment by mywtfmp3** [comment]
Got it.

**Comment by mywtfmp3** [comment]
I was busy when replying you. I have to give a thank you for your answer.
