### ISSUE TITLE
How to show all the elements loaded via Builder?

### ISSUE THREAD

**Issue by FFY00** [gtkd-developers/GtkD#246]
I don't know if this is the right place to ask but I am having some problems using `Builder`.
I did my design in Glade and I am importing the `.ui` file using `builder.addFromResource()`.
The `.ui` file contains two components, a `GtkHeaderBar` (`headerBar`) and a `GtkWindow` (`windowContent`).
After loading the file, I proceed to set the title bar. `this` is an `ApplicatonWindow`.
```
this.setTitlebar(headerBar);
this.add(windowContent);
```
This works, it shows an empty window with my header bar. **(1)**
Now, I want to show all the other elements. I tried the following.
```
this.showAll();
```
I also tried using `windowContent` instead of `this`. It sort of works. It shows the window with all the elements but the header bar is shown in a different window. Basically `showAll()` creates two windows, one with my design and other with the header bar. **(2)**

#### (1) Without `showAll()`
![deepinscreenshot_select-area_20180630144749](https://user-images.githubusercontent.com/11718923/42125764-9581726e-7c74-11e8-9f11-19b8d860f590.png)

#### (2) With `showAll()`
![deepinscreenshot_select-area_20180630144712](https://user-images.githubusercontent.com/11718923/42125778-b1ae8efe-7c74-11e8-9c5d-574a20e97cd5.png)
I also get some weird behavior from the populated window when I interact with the window that has the header bar. Sometimes part of it turns black and sometimes some of the elements disappear.

Thanks in advance if anyone is able to help.

**Comment by FFY00** [comment]
I enabled it and put the `headerBar` inside `windowContent`. The second windows still opens but now the header bar is the right window.

![deepinscreenshot_select-area_20180630163049](https://user-images.githubusercontent.com/11718923/42126658-f8b4a956-7c82-11e8-9f82-58016f813895.png)
I still get some rendering problems in the populated window.

**Comment by MikeWey** [comment]
How are you using `windowContent` within your application?

You would usually do something like this:

```D
auto window = cast(Window)builder.getObject("windowContent");
window.showAll();
```

**Comment by FFY00** [comment]
My project structure is based on GtkdApp

I have a custom `ApplicationWindow` which represent my main application. [See this](https://gitlab.com/csoriano/GtkDApp/blob/master/src/appwindow.d).

In the constructor, I am casting the elements and doing this.
```
this.add(windowContent);
this.showAll();
```

Result:
![deepinscreenshot_select-area_20180630164359](https://user-images.githubusercontent.com/11718923/42126768-cd685f70-7c84-11e8-9e03-0b82e82cea4d.png)

**Comment by MikeWey** [comment]
You get two windows because gtk is displaying both the ApplicationWindow from your code and the Window from the glade file.

You can shao the `windowContent` from the OnActivate handler, and possibly use a GtkApplicationWindow in glade.

Or take the same route as the example in the linked gitlab repo and don't use a toplevel widget as the `windowContent` and add that to your application window. (it's a GtkLabel in case of the exmple app)

**Comment by FFY00** [comment]
So, I changed the `.ui` file to use `GtkApplicationWindow` and edited [`app.d` to this](https://gist.github.com/FFY00/88f0a941901d456fc1121efe274b13d5). When running the program, it doesn't show any window and exits normaly. Any ideas why?

**Comment by FFY00** [comment]
Nevermind, fixed with `window.setApplication(this)`.

Thanks for all of your help! It was extremely helpful :smile:
