### ISSUE TITLE
MainContext.defaulx?

### ISSUE THREAD

**Issue by kirbyfan64** [gtkd-developers/GtkD#247]
`g_main_context_default` is bound as `MainContext.defaulx`. Is this a typo?

**Comment by MikeWey** [comment]
'default' is a keyword in D so we can't use that name.
But 'defaulx' is a odd replacement, i'll check if it can be brought more in line with the replacements for the other keywords.

**Comment by MikeWey** [comment]
Commit 9dbd03e replaces 'defaulx' with 'default'.
