### ISSUE TITLE
Support gtksourceview4

### ISSUE THREAD

**Issue by jbicha** [gtkd-developers/GtkD#256]
[gtksourceview](https://wiki.gnome.org/Projects/GtkSourceView) now offers version 4. It is still for gtk3. I expect a future gtk4 version will be named gtksourceview5.

The only part of core GNOME yet to switch to gtksourceview4 is [sushi](https://gitlab.gnome.org/GNOME/sushi/issues/6) (as of the development 3.31 series).

It would be nice if gtk-d could switch to gtksourceview4 too.

References
----------------
- https://mail.gnome.org/archives/desktop-devel-list/2018-May/msg00007.html
- https://developer.gnome.org/gtksourceview/stable/porting-guide-3-to-4.html

**Comment by MikeWey** [comment]
We would probably want to have both available to avoid breaking existing projects using the gtksourceview3 binding.

**Comment by jbicha** [comment]
Ok, do you have any idea which projects are using gtksourceview for D?

The only thing using gtk-d in Debian is _tilix_ (but I understand Debian isn't everything). _tilix_ only uses _gtkd_ and _vted_.

**Comment by MikeWey** [comment]
I think the changes are small enough, so we can update to gtksourceview4.

**Comment by worldofpeace** [comment]
Why does `paths.d` use the old library name?
* https://github.com/gtkd-developers/GtkD/blob/master/generated/gtkd/gtkd/paths.d#L134

**Comment by MikeWey** [comment]
Probably because that file isn't generated from gir files, the one you want to use can be found here:

https://github.com/gtkd-developers/GtkD/blob/master/generated/sourceview/gsv/c/functions.d#L31

I'll update the one in paths.d
