### ISSUE TITLE
Assertion Failed on TextView when using gobject.Signals

### ISSUE THREAD

**Issue by nanotyrannus** [gtkd-developers/GtkD#265]
Using version 3.8.5. Not sure if I'm using `Signals` correctly. When trying to connect to `key-press-event` on TextView, it generates `GLib-GObject-CRITICAL **: g_value_get_object: assertion 'G_VALUE_HOLDS_OBJECT (value)' failed` and `keyval` is always 0.

```
import std.stdio;
import gtk.Main;
import gtk.MainWindow;
import gtk.Widget;
import gdk.Event;
import gtk.TextView;
import gobject.Signals;

void main(string[] args)
{
	Main.init(args);
	auto w = new MyWindow();
	Main.run();
}

class MyWindow: MainWindow {
	this() {
		super("Test");
		setDefaultSize(200, 200);
		auto view = new TextView();
		Signals.connect(view, "key-press-event", delegate bool(Event e, Widget w){
                        e.key.keyval.writeln;
			return false;
		});
		add(view);
		showAll();
	}
}```

**Comment by MikeWey** [comment]
With gobject.Signals the first parameter of the delegate/callback is the widget receiving the signal.

So you will need to swap the two parameters:
```
Signals.connect(view, "key-press-event", delegate bool(Widget w, Event e){
	e.key.keyval.writeln;
	return false;
});
```
Or pass `ConnectFlags.SWAPPED` to connect:
```
Signals.connect(view, "key-press-event", delegate bool(Event e, Widget w){
	e.key.keyval.writeln;
	return false;
}, ConnectFlags.SWAPPED);
```
And there is always the option to use `addOnKeyPress`:
```
view.addOnKeyPress(delegate bool(Event e, _){
	e.key.keyval.writeln;
	return false;
});
```
With the added benefit of getting an error at compiletime when using the wrong parameters.

**Comment by nanotyrannus** [comment]
Thank you much, that works! I missed that in the docs, and for some reason my IDE didn't know of the existence of`TextView.addOnKeyPress`.
