### ISSUE TITLE
Provide GTK Windows runtime in .zip format for automated builds

### ISSUE THREAD

**Issue by yatima1460** [gtkd-developers/GtkD#268]
My big project using GtkD:

 https://github.com/yatima1460/Drill 

[![Build Status](https://travis-ci.org/yatima1460/Drill.svg?branch=master)](https://travis-ci.org/yatima1460/Drill)
[![GitHub issues](https://img.shields.io/github/issues/yatima1460/Drill.svg)](https://github.com/yatima1460/Drill/issues)
[![GitHub forks](https://img.shields.io/github/forks/yatima1460/Drill.svg)](https://github.com/yatima1460/Drill/network)
[![GitHub stars](https://img.shields.io/github/stars/yatima1460/Drill.svg)](https://github.com/yatima1460/Drill/stargazers)
[![GitHub license](https://img.shields.io/github/license/yatima1460/Drill.svg)](https://github.com/yatima1460/Drill/blob/master/LICENSE)

now works on Linux and it's almost working on OSX too.

I would like to build a Windows version on Travis too and dump the necessary GTK .dlls inside a portable zip with the executable and then maybe create an installer too.

The GTK runtime you provide on the website is the best one I've tried, can you provide a .zip version instead of the .exe installer?
And if you built that GTK yourself, how did you do it?

Thanks

**Comment by MikeWey** [comment]
The current installer uses the binaries from msys2.

I'll see about creating the zip file, but i'll have to check if GtkD handles a GTK that is not in the PATH properly.

**Comment by yatima1460** [comment]
I can confirm it works

I just dumped the .dll inside my executable that uses GtkD and the application started

The only bug is that some icons didn't appear, but that's normal because there is no theme installed

**Comment by yatima1460** [comment]
Also if your website is not hosted on Github Pages I recommend to add the zip binaries here on GitHub Releases so me and other devs will not destroy your bandwidth

**Comment by yatima1460** [comment]
Or we could setup a repository using Travis Windows to create them daily.
(does Travis even support MSYS2)?

I am trying with vcpkg but it seems Travis just crashes

https://github.com/yatima1460/GTK3-Windows-x64/blob/master/.travis.yml

**Comment by yatima1460** [comment]
@MikeWey 
I found the best solution, forget your MSYS .dlls, [vcpkg](https://github.com/microsoft/vcpkg) can build fresh GTK dlls now on Windows but you need to add support for it

**Comment by yatima1460** [comment]
The current problem is that `Loader.d` can't find the .dlls even when they are renamed and put in the same folder of my executable

First if can't find `libgdk-3-0.dll` because vcpkg generates a different name, after renaming it loads the .dll but it needs `libgtk-3-0.dll` but after renaming that too it doesn't work

**Comment by yatima1460** [comment]
built them if you need them

https://github.com/yatima1460/GTK3-Windows-Binaries/releases/tag/3.22.19-2

**Comment by MikeWey** [comment]
Nice, did you sort out the naming issue with the dll's. It looks like that compared to the other platforms `vcpkg` doesn't include the so version in the dll name?

**Comment by yatima1460** [comment]
Nope, can't understand why, I renamed both libraries but it can't find libgtk-3-0.dll even when it's in the same folder but can find libgdk-3-0.dll

`object.Exception@GtkD-3.8.5\generated\gtkd\gtkd\Loader.d(125): Library load failed (libgtk-3-0.dll): The specified module could not be found.`

The only reason I can think of is that vcpkg adds the name as a #define 

Maybe I can try to rename these:

https://github.com/gtkd-developers/GtkD/blob/5d99cc2062a1cd6e5112d77eb32c6546dc9a9eb0/src/gtkd/paths.d#L72

**Comment by MikeWey** [comment]
That would be because `libgtk-3-0.dll` depends on the other libraries which it can no longer find because they have been renamed.

For renaming the libraries you will need to change these:

https://github.com/gtkd-developers/GtkD/blob/master/generated/gtkd/gobject/c/functions.d#L32

They are in the same place for the other packages.

**Comment by MikeWey** [comment]
Does Travis support 7zip?

https://github.com/gtkd-developers/Gtk-Installer/releases/tag/v3.24.8

**Comment by yatima1460** [comment]
Yes, Travis on Windows is Git Bash with 7zip already installed

And even if it wasn't there you could wget it!
Or use choco to install it too

**Comment by yatima1460** [comment]
Thanks

I will check if I can find a way to fix the vcpkg gtk

**Comment by MikeWey** [comment]
wingtk (#270) also uses different names for the gtk dll's so i'll update the generator to generate the different possibilities for Windows.
