### ISSUE TITLE
Dead link in the docs

### ISSUE THREAD

**Issue by John-Colvin** [gtkd-developers/GtkD#271]
https://api.gtkd.org/gtkglc.glgdk.html is 404

I got there from https://api.gtkd.org/glgdk.GLDrawableT.html

**Comment by MikeWey** [comment]
Looks like adrdox doesn't generate the page because it doesn't contain any documentation, but it still links to it.

I have manually removed the link for now. But there might be more cases like this.

**Comment by MikeWey** [comment]
I think this is fixed in the new version of adrdox.
