### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by FFY00** [gtkd-developers/GtkD#272]
```
ldc: Unknown command line argument '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'.
```

**Comment by MikeWey** [comment]
The GtkD makefile isn't adding these flags, ldc might be picking them up from your systems configuration?

**Comment by MikeWey** [comment]
More specifically the LDFLAGS environment variable is set to these flags as they are defined in /etc/makepkg.conf

**Comment by FFY00** [comment]
Yes, but aren't those valid flags?

I haven't been able to look at this because I have been away without a computer. I come home today.

If you want to look at this yourself uncomment the check function in https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/gtkd and try to build the package.

**Comment by MikeWey** [comment]
ldc doesn't have the `-Wl,` flag only the same `-L` flag dmd uses to pass arguments to the linker.

You probably also want to set `DC` to ldc in the check function.
