### ISSUE TITLE
Gtk-WARNING **: Allocating size to GtkApplicationWindow

### ISSUE THREAD

**Issue by yatima1460** [gtkd-developers/GtkD#274]
I have a list with a scrollbar and a simple window and when calling:
```D
TreeIter it = liststore.createIter();
``` 
https://github.com/yatima1460/Drill/blob/4741170ac8ce406ca52c51d522d44054aec7bc20/Source/Frontend/GTK/Window.d#L185

I immediately have this warning:

```bash
(drill-search-gtk:29727): Gtk-WARNING **: Allocating size to GtkApplicationWindow 0x55c6761702a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

Is this a GTK problem or a GTKd problem?
I can't find anything online

Thanks

**Comment by MikeWey** [comment]
I believe this is a GTK issue, possibly this one: https://gitlab.gnome.org/GNOME/gtk/issues/632

**Comment by yatima1460** [comment]
The fact that I'm just using a simple window with an entry text, a list and a scrollbar and have this bug when creating an empty iterator is worrisome

But mainly that it's open for 3+ years

**Comment by yatima1460** [comment]
Do you know any way to disable GTK warnings?
I don't really care about it and everything works perfectly

**Comment by yatima1460** [comment]
@MikeWey 

calling this after adding the columns makes the warning disappear
`treeview.setFixedHeightMode(true);`
