### ISSUE TITLE
Doesn't install .pc files

### ISSUE THREAD

**Issue by yurivict** [gtkd-developers/GtkD#276]
There are lines in the makefile that install them, but they probably aren't in the default path.

Could you please define build/install targets that would install all commonly requires parts, including .pc files and shared libs?

Thanks!
Yuri

**Comment by MikeWey** [comment]
The makefile currently installs them in `$(DESTDIR)$(prefix)/$(libdir)/pkgconfig` which defaults to: `/usr/local/lib/pkgconfig` which should be the correct location, only `/usr/local` isn't always in the default pkg-config path.
