### ISSUE TITLE
Dmd warns deprecation message while building 

### ISSUE THREAD

**Issue by HossainAdnan** [gtkd-developers/GtkD#280]
While building gtk-d, dmd gives the following deprecation message:

>../../.dub/packages/gtk-d-3.8.3/gtk-d/generated/gtkd/glib/Spawn.d(305,3): Deprecation: foreach: loop index implicitly converted from size_t to int

**Comment by MikeWey** [comment]
As far as i know this is already fixed in GtkD v3.9.0 ?

**Comment by HossainAdnan** [comment]
Confirmed. Closing.
