### ISSUE TITLE
GDC does not work

### ISSUE THREAD

**Issue by Kozzi11** [gtkd-developers/GtkD#282]
I am trying to build gtkd with gdc (gcc-9.2) and I am getting many errors like this:

```
   /usr/bin/ld: error: generated/gtkd/gio/UnixSocketAddress.pic.o: multiple definition of '_DT40_D3gio13SocketAddress13SocketAddress8__mixin926getSocketConnectableStructMFbZPS3gio1c5types18GSocketConnectable'
```

**Comment by MikeWey** [comment]
I will have to take a closer look when i'm back home, but if the other compilers don't have this issue it might be a GDC issue.

**Comment by Kozzi11** [comment]
https://forum.dlang.org/post/etmhysuzxhozjjlnbhmr@forum.dlang.org

**Comment by Kozzi11** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92216

**Comment by Kozzi11** [comment]
Already fixed by GDC devs
