### ISSUE TITLE
How to avoid the cmd window ?

### ISSUE THREAD

**Issue by vinodvinu** [gtkd-developers/GtkD#284]
Hi,
Thanks for the library. I have tested it successfully, But there is a CMD window is appearing first. I dont want this. How to avoid this CMD window.
Note - At first, i compiled the gtkD as 32 bit build. My PC is 64 bit. So i cant run the compiles hello app. There is a 3+ MB sized exe file, but i can't run it. Then i compiled the gtkD again with 64 bit command. And then everything works perfectly except this CMD window stuff.

**Comment by MikeWey** [comment]
Passing `-L=/SUBSYSTEM:windows` to dmd should take care of the console window.

This tells the linker that your application doesn't require a console window.

**Comment by vinodvinu** [comment]
@MikeWey 
Thanks for the reply.  I just apply this command right after the "dmd" and it shows an error msg like "module SUBSYSTEM:windows is in file 'L=\SUBSYSTEM:windows.d' which cannot be read"

**Comment by MikeWey** [comment]
Try it without the `=` like this: `-L/SUBSYSTEM:WINDOWS`

`-L` tells dmd to pass the command that follows to the linker, so a 
missing file error is a bit strange.

Also in your error message the starting dash `-` is missing and the 
wrong slash is used.
