### ISSUE TITLE
404 link for what kind of wrap

### ISSUE THREAD

**Issue by joelcnz** [gtkd-developers/GtkD#285]
[has the link that is broken.](https://api.gtkd.org/gtk.TextView.TextView.setWrapMode.html)

**Comment by MikeWey** [comment]
I manually fixed the link. But adrdocs should be able to link it correctly.

**Comment by joelcnz** [comment]
The link is still broken. How do I open the adrdocs?

**Comment by MikeWey** [comment]
It's working for me, you may need to hit `F5` to reload the page.

adrdocs is the tool used to generate the documentation, and it can be found here: https://github.com/adamdruppe/adrdox

**Comment by joelcnz** [comment]
Ok, got the page coming up - thanks MikeWey.
