### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by andre2007** [gtkd-developers/GtkD#295]
Is there any chance to have for GtkD another license than LGPL?

LGPL is avoided by companies as much as possible. Although GTK itself is also LGPL, here only dynamic linked binaries are used and therefore it could be used. But GtkD cannot be used at all, as here coding is statically linked, therefore it is a big no-go ):

**Comment by MikeWey** [comment]
No, some past contributors don't want there code available under a different licence.

I don't think `dub` supports it , but you can build GtkD as a shared library using:
```
make shared
```

**Comment by andre2007** [comment]
Thanks for clarification. I  am not even allowed to build the shared object file of GtkD. To avoid license issues companies have strict rules.

I will try wheter the C interface of gtk3 can be used directly and unfortunately need to avoid GtkD ):
