### ISSUE TITLE
Can't post to the GtkD forum

### ISSUE THREAD

**Issue by mark-summerfield** [gtkd-developers/GtkD#298]
I created a login for https://forum.gtkd.org/groups/GtkD/ and tried to post but all that happened was some red text appeared: "findAndModify failed."

My post was:

I'm trying to learn GtkD as a newcomer to Gtk. (I'm familiar with Qt, wx, and Tkinter.)

There seem to be two "styles" of GtkD programming: Gtk2-style and
Gtk3-style (see for example
[gtkdnotes]<https://gitlab.com/9898287/gtkdnotes/-/blob/master/notes/2.%20Getting%20Started.md>).

Is there any reason I should prefer one to the other? Are there examples showing how to translate from Gtk2-style to Gtk3-style?

Are there any good up-to-date books on GtkD? (Or on Gtk, but that are easy to understand in terms of D?)

**Comment by mark-summerfield** [comment]
Actually, despite the fact that it gave an error message, it did in fact post. So now I've posted 7 copies of the message:-(

**Comment by MikeWey** [comment]
It looks like there is something wrong with the mongodb instance, the 
forum is completely down now :(

Mike

**Comment by MikeWey** [comment]
Should be fixed now.
