### ISSUE TITLE
Button.setImage(new Image(StockID.name)) doesn't work

### ISSUE THREAD

**Issue by mark-summerfield** [gtkd-developers/GtkD#300]
Using `Button.setImage` doesn't seem to work with stock item images.
Attached is a tiny runnable example that shows a "missing icon" icon instead of the wanted icon.
[b1bug.zip](https://github.com/gtkd-developers/GtkD/files/4224197/b1bug.zip)

```
        optionsButton = new Button("_Options");
        // Supposed to work but doesn't:
        optionsButton.setImage(new Image(StockID.PREFERENCES));
        helpButton = new Button(StockID.HELP);
```

**Comment by MikeWey** [comment]
The code calls a different constructor than the one accepting a StockID because the IconSize is missing. The value that is in the StockID enum is passed to the constructor expecting a filename.

This should work:
```
optionsButton = new Button("_Options");
optionsButton.setImage(new Image(StockID.PREFERENCES, IconSize.BUTTON));
```

**Comment by mark-summerfield** [comment]
That didn't work for me, but this variation did:
```
        optionsButton.setImage(new Image(StockID.PREFERENCES,
                                         IconSize.fromName("BUTTON")));
```
