### ISSUE TITLE
function gtk.Widget.Widget.addOnDraw is deprecated

### ISSUE THREAD

**Issue by iK4tsu** [gtkd-developers/GtkD#301]
I want to work with `gtk.DrawingArea`, however the only way (that I know of) to draw is to connect with the signal `addOnDraw`. From my research the upcoming Gtk release, Gtk4, the `gtk.Widget` won't have the `addOnDraw` signal, and instead `gtk.DrawingArea` will have a `gtk_drawing_area_set_draw_func`, link <https://developer.gnome.org/gtk4/stable/GtkDrawingArea.html#gtk-drawing-area-set-draw-func>.

How should I proceed now? Should I keep using the `addOnDraw` signal until the new major update and then fix it when it breaks, or is there other way to do it?

**Comment by MikeWey** [comment]
Currently the only thing you can do is keep using the signal and change the implementation when switching to GTK4.

**Comment by iK4tsu** [comment]
Ok, thank you!
