### ISSUE TITLE
Undefined references with gtk.c.types enums on DMD

### ISSUE THREAD

**Issue by streaksu** [gtkd-developers/GtkD#308]
The following error at linking can be found when compiling a GtkD application with DMD `v2.093.1` but will not be found with LDC `1.22.0`. The version of GtkD is `3.9.0`.
```
Undefined reference to '_D3gtk1c5types15GtkResponseType6__initZ'
```
This only happens as far as I tested when using the enumeration `ResponseType` defined [here](https://github.com/gtkd-developers/GtkD/blob/v3.9.0/generated/gtkd/gtk/c/types.d#L2810). The smallest snippet I found able to replicate the issue is
```d
void example() {
    import gtk.Dialog;
    import gtk.Window;

    auto win = new Window("a");
    auto dialog = new Dialog(
        "Security info",
        win,
        DialogFlags.DESTROY_WITH_PARENT,
        ["Close"],
        [ResponseType.CLOSE]
    );

    dialog.run();
}
```
And it is linked with
```
dmd -of=test <some object files> -L=--allow-shlib-undefined -defaultlib=phobos2 -debuglib=phobos2 -L-L/usr/lib// -L-lgtkd-3 -L-ldl -L=-lwebkit2gtk-4.0 -L=-lgtk-3 -L=-lgdk-3 -L=-lz -L=-lpangocairo-1.0 -L=-lpango-1.0 -L=-lharfbuzz -L=-latk-1.0 -L=-lcairo-gobject -L=-lcairo -L=-lgdk_pixbuf-2.0 -L=-lsoup-2.4 -L=-lgio-2.0 -L=-ljavascriptcoregtk-4.0 -L=-lgobject-2.0 -L=-lglib-2.0
```

I am using the versions packed by Arch Linux of DMD and GtkD if that happens to be relevant.

**Comment by streaksu** [comment]
A temporary fix is to compile `gtk.c.types` as part of the application, which makes me think this probably has to do with some symbols being excluded from the built libraries.

**Comment by MikeWey** [comment]
The different D compilers are not binary compatible, this means that since the version of GtkD that is packaged by Archlinux is build with LDC. you will need to use LDC to build your applications.

**Comment by streaksu** [comment]
Oh I see, I will close this then as it doesn't really have to do with the project but the packaging efforts and the current state of D binary compatibility.
Sorry for the inconvenience.
