### ISSUE TITLE
[Question] What's the state of GtkD4?

### ISSUE THREAD

**Issue by Godnyx** [gtkd-developers/GtkD#323]
Like anyone, I'm wondering what's the state of GtkD4. Is anyone working on it?

**Comment by MikeWey** [comment]
I'm still working on it only a little low no time.

In it's current state GtkD4 compiles and runs, while updating the demo's i haven't found any serious bugs yet, only some convenience functions that where there in v3 are still missing.

**Comment by jonathanballs** [comment]
I would be happy to lend a hand and help get this pushed if you need any help @MikeWey

**Comment by Godnyx** [comment]
Thanks a lot everyone for your hard support!

**Comment by MikeWey** [comment]
> I would be happy to lend a hand and help get this pushed if you need any help @MikeWey

Some help updating the demos and reporting/fixing the issues that arise would help a lot.
