### ISSUE TITLE
[QUESTION] MainWindow or ApplicationWindow?

### ISSUE THREAD

**Issue by Godnyx** [gtkd-developers/GtkD#327]
I'm very new to Gtk and GtkD and I'm trying to learn it. In the [gtkDcoding](https://gtkdcoding.com/) the examples (at least the first ones) using the "MainWindow" class to create applications. The demos in the repo here use the "ApplicationWindow". Which one should I use and why?

**Comment by MikeWey** [comment]
In new code it's best to use ApplicationWindow, it's the only one of the two that is available in gtk4 so it makes porting in the future easier.

**Comment by Godnyx** [comment]
Thanks a lot! Is there a small case that you are familiar with the " gtkDcoding" and you know other things that should change as well?

**Comment by MikeWey** [comment]
gtkDcoding uses Main.init / Mail.run instead of using gtk.Application, but that go's hand in hand with gtk.ApplicationWindow.

Other that that i am not to familiar with the code used by gtkDcoding.

**Comment by Godnyx** [comment]
Thanks a lot!
