### ISSUE TITLE
How to Wrap GObject Introspection-based libraries for begginers

### ISSUE THREAD

**Issue by JeysonFlores** [gtkd-developers/GtkD#344]
Hi, I'm new to GtkD and I haven't used it so much, but I've used it enough to be able to perform some tasks. However I need to use some GIR-based libraries like [libhandy-1](https://gitlab.gnome.org/GNOME/libhandy) ([there's a wrapper for libhandy](https://github.com/LunaTheFoxgirl/d-handy) but it's for libhandy-0) and [Granite](https://github.com/elementary/granite). I know I need to write the wrapper in order to generate it however I don't even know where to start. Is there any documentation for writing wrappers?

**Comment by MikeWey** [comment]
If the library doesn't need any manual intervention just running:

`girtod -i Handy-1.gir`

will generate a binding for the library in the current working directory.
 `girtod` can be found here: https://github.com/gtkd-developers/gir-to-d

For an example of a library that needs manual changes see the D binding of ATK: https://github.com/gtkd-developers/AtkD/blob/master/src/APILookup.txt

**Comment by JeysonFlores** [comment]
Ok, I installed gir-to-d.
It generated libhandy-1 wrappers successfully however if I try to generate Granite's wrappers it gives me a segmentation fault:
```bash
$ girtod -i Granite-1.0.gir
Segmentation fault
```
and if I execute it with the parameter  of --print-files it gives me this result:
```bash
$ girtod -i Granite-1.0.gir --print-files
out/granite/c/functions.d
out/granite/c/types.d
out/granite/DrawingBufferSurface.d
out/granite/DrawingColor.d
out/granite/DrawingUtilities.d
out/granite/ServicesContractorProxy.d
Segmentation fault
```

**Comment by MikeWey** [comment]
i've fixed the segfault in gir-to-d: https://github.com/gtkd-developers/gir-to-d/commit/739a67d58e98a51d8c064a175f74e875f367efdb

Granite being a vala library might cause some more problems.

**Comment by JeysonFlores** [comment]
Thanks!
