### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ximion** [gtkd-developers/GtkD#346]
Hi!
The last GtkD release was more than two years ago, and quite a lot of changes have accumulated in the master branch. In fact, the current GtkD release doesn't even build anymore with recent LDC versions, which is why I would probably need to package a Git snapshot of this project for Debian next, in order to get all the fixes.
Would it be possible to tag a new release instead?
Thank you!

**Comment by MikeWey** [comment]
Tagged v3.10.0.

**Comment by ximion** [comment]
Thank you! :-)
