### ISSUE TITLE
wrapper for Dialog.getHeaderBar returns Widget instead of HeaderBar

### ISSUE THREAD

**Issue by hyOzd** [gtkd-developers/GtkD#348]
`Dialog.getHeaderBar` returns a `Widget` instead of `HeaderBar`. It seems like this was manually fixed for `getContentArea` and `getActionArea` functions. I think a similar wrapper should be added for `getHeaderBar` function. I tried this by manually editing the generated code and it works:

```
	//Return the corect class instead of Widget
	/**
	 * Returns the header bar of dialog. Note that the
	 * headerbar is only used by the dialog if
	 * the use-header-bar property is TRUE.
	 * Since: 3.12
	 * Returns: the header bar
	 */
	public HeaderBar getHeaderBar()
	{
		auto p = gtk_dialog_get_header_bar(gtkDialog);
		if(p is null)
		{
			return null;
		}
		return new HeaderBar(cast(GtkHeaderBar*) p);
	}
```

**Comment by MikeWey** [comment]
I looks like the gir files have improved for cases like this and after regenerating the code the `getHeaderBar` function now returns a HeaderBar.

https://github.com/gtkd-developers/GtkD/blob/master/generated/gtkd/gtk/Dialog.d#L367

Fixed in commit: 43060ab8b88c34be7e617a89bcb41c0e6e3f4637
