### ISSUE TITLE
Create new tag/release for 3.11

### ISSUE THREAD

**Issue by hrauchgh** [gtkd-developers/GtkD#353]
What's the current status with regard to a 3.11 tag? (I'm mainly asking because e.g. support for the latest gtk3 libs has already been added quite some time ago and I wonder why that obviously hasn't "sufficed" for creating a new tag?)

**Comment by akinomyoga** [comment]
I also would like to request a new release since Tilix wants to use `vte.Terminal.pasteText` added in [`43060ab`](https://github.com/gtkd-developers/GtkD/commit/43060ab8b88c34be7e617a89bcb41c0e6e3f4637#diff-788067c03551f4286880814d96a14ee44cae84a463219b62360930d76d511437R1054-R1057).

**Comment by MikeWey** [comment]
Tagged current master as 3.11.

**Comment by akinomyoga** [comment]
Thank you for your quick action and response! Can I assume it will soon be available on the DUB repository?

**Comment by akinomyoga** [comment]
I confirm that 3.11.0 is now available on the DUB repository. Thanks!
