### ISSUE TITLE
GDI object leak in example cairo_clock (& in DrawingArea)

### ISSUE THREAD

**Issue by ghost** [gtkd-developers/GtkD#58]
under win7 32bit. compiled with dmd 2.063.2. using gtk+ 3.6.1

- compile and run the example cairo_clock.
- during 30 seconds, resize the window in an "unrealistic way" (like a nut)
- check the GDI objects count in the task man, it can stop on increasing.

remove the onDraw listener, recompile, recheck: no more leak.
The problem append even in a simple window with an empty onDraw event.

**Comment by MikeWey** [comment]
With the 3.0.0 release the non Scoped version is marked as deprecated.
