### ISSUE TITLE
Buttons in a window get selected while the window is being resized

### ISSUE THREAD

**Issue by ghost** [gtkd-developers/GtkD#68]
Here's an example:
http://www.youtube.com/watch?v=_kl6hqiIEpI&feature=youtu.be

I'm on Win7 64bit, building in 32bit mode using DMD 2.063.2.
Tested using `gtkD-2.3.0.zip` and `GTK Runtime version 3.8 (32 bits).`

This was running the `GtkD\demos\gtkD\TestWindow` example.

The video doesn't show it, but if I resize the window rightwards only, the `cancel` button gets selected, and then if I further resize it rightwards the `quit` button gets selected. Then resizing it back leftwards selects the `cancel` button and then the `ok` button.

**Comment by MikeWey** [comment]
I can't reproduce this with GTK 3.18.
